/* ───────────────────────────────────────────────
 * 성경 용어 사전 데이터  (glossary.js)
 * index.html 과 같은 폴더에 두세요.
 *
 * 항목 추가/수정:
 *   '표제어': { category:'인물', desc:'설명', ref:'성경 위치' },
 *   category 는 인물 / 지명 / 용어 중 하나
 * ─────────────────────────────────────────────── */

window.GLOSSARY = {

  // ── 인물 ──
  '아담': { category:'인물', desc:'하나님이 흙으로 지으신 최초의 사람. 모든 인류의 조상이며 하와와 함께 에덴동산에 살다가 범죄로 추방되었다.', ref:'창세기 2~3장' , en:'Adam', origin:'אָדָם', pron:'아담' },
  '하와': { category:'인물', desc:'아담의 아내이자 모든 산 자의 어머니. 뱀의 유혹으로 선악과를 먹어 아담과 함께 죄에 빠졌다.', ref:'창세기 3장' , en:'Eve', origin:'חַוָּה', pron:'하바' },
  '가인': { category:'인물', desc:'아담과 하와의 맏아들. 동생 아벨을 시기해 죽인 최초의 살인자.', ref:'창세기 4장' , en:'Cain', origin:'קַיִן', pron:'카인' },
  '아벨': { category:'인물', desc:'아담과 하와의 둘째 아들. 양치는 자로 정성된 제물을 드렸으나 형 가인에게 죽임을 당했다.', ref:'창세기 4장' , en:'Abel', origin:'הֶבֶל', pron:'헤벨' },
  '셋': { category:'인물', desc:'아담과 하와의 셋째 아들. 아벨을 대신한 경건한 자손의 계보를 이었다.', ref:'창세기 4~5장' , en:'Seth', origin:'שֵׁת', pron:'셰트' },
  '에녹': { category:'인물', desc:'죽음을 보지 않고 하나님과 동행하다 하늘로 들려 올라간 사람.', ref:'창세기 5장' , en:'Enoch', origin:'חֲנוֹךְ', pron:'하노크' },
  '므두셀라': { category:'인물', desc:'969세로 성경에서 가장 오래 산 사람. 에녹의 아들이자 노아의 할아버지.', ref:'창세기 5장' , en:'Methuselah', origin:'מְתוּשֶׁלַח', pron:'메투셸라흐' },
  '노아': { category:'인물', desc:'홍수 심판 때 방주를 지어 가족과 동물을 구한 의인. 하나님과 무지개 언약을 맺었다.', ref:'창세기 6~9장' , en:'Noah', origin:'נֹחַ', pron:'노아흐' },
  '셈': { category:'인물', desc:'노아의 아들. 셈족(히브리·아랍 등)의 조상.', ref:'창세기 9~11장' , en:'Shem', origin:'שֵׁם', pron:'셈' },
  '함': { category:'인물', desc:'노아의 아들. 아버지의 허물을 가리지 않아 그 아들 가나안이 저주받았다.', ref:'창세기 9장' , en:'Ham', origin:'חָם', pron:'함' },
  '야벳': { category:'인물', desc:'노아의 아들. 여러 민족의 조상이 되었다.', ref:'창세기 10장' , en:'Japheth', origin:'יֶפֶת', pron:'예페트' },
  '니므롯': { category:'인물', desc:'함의 자손으로 용맹한 사냥꾼이자 바벨 왕국을 세운 자.', ref:'창세기 10장' , en:'Nimrod', origin:'נִמְרוֹד', pron:'니므로드' },
  '아브라함': { category:'인물', desc:'믿음의 조상. 갈대아 우르에서 가나안으로 부르심을 받았고 하나님과 언약을 맺어 큰 민족의 조상이 되었다. 본래 이름은 아브람.', ref:'창세기 12~25장' , en:'Abraham', origin:'אַבְרָהָם', pron:'아브라함' },
  '사라': { category:'인물', desc:'아브라함의 아내. 나이 들어 약속의 아들 이삭을 낳았다. 본래 이름은 사래.', ref:'창세기 17~23장' , en:'Sarah', origin:'שָׂרָה', pron:'사라' },
  '롯': { category:'인물', desc:'아브라함의 조카. 소돔에 살다가 멸망 직전 천사의 인도로 피신했다.', ref:'창세기 13~19장' , en:'Lot', origin:'לוֹט', pron:'로트' },
  '하갈': { category:'인물', desc:'사라의 여종으로 이스마엘의 어머니.', ref:'창세기 16장, 21장' , en:'Hagar', origin:'הָגָר', pron:'하가르' },
  '이스마엘': { category:'인물', desc:'아브라함과 하갈의 아들. 아랍 민족의 조상으로 여겨진다.', ref:'창세기 16~25장' , en:'Ishmael', origin:'יִשְׁמָעֵאל', pron:'이슈마엘' },
  '이삭': { category:'인물', desc:'아브라함과 사라의 약속의 아들. 리브가와 결혼해 에서와 야곱을 낳았다.', ref:'창세기 21~27장' , en:'Isaac', origin:'יִצְחָק', pron:'이츠하크' },
  '리브가': { category:'인물', desc:'이삭의 아내이며 에서와 야곱의 어머니.', ref:'창세기 24~27장' , en:'Rebekah', origin:'רִבְקָה', pron:'리브카' },
  '야곱': { category:'인물', desc:'이삭의 아들이며 이스라엘 열두 지파의 조상. 하나님과 씨름한 뒤 이스라엘이라는 이름을 받았다.', ref:'창세기 25~50장' , en:'Jacob', origin:'יַעֲקֹב', pron:'야아콥' },
  '에서': { category:'인물', desc:'이삭의 큰아들이자 야곱의 형. 장자권을 팥죽에 팔았고 에돔 족속의 조상이 되었다.', ref:'창세기 25~36장' , en:'Esau', origin:'עֵשָׂו', pron:'에사브' },
  '라반': { category:'인물', desc:'리브가의 오빠이자 야곱의 외삼촌·장인. 야곱이 레아와 라헬과 결혼한 집안.', ref:'창세기 29~31장' , en:'Laban', origin:'לָבָן', pron:'라반' },
  '레아': { category:'인물', desc:'야곱의 첫 아내. 유다 등 여러 아들을 낳았다.', ref:'창세기 29장 이하' , en:'Leah', origin:'לֵאָה', pron:'레아' },
  '라헬': { category:'인물', desc:'야곱이 사랑한 아내. 요셉과 베냐민의 어머니.', ref:'창세기 29~35장' , en:'Rachel', origin:'רָחֵל', pron:'라헬' },
  '요셉': { category:'인물', desc:'야곱의 아들. 형들에게 팔려 애굽으로 갔으나 총리가 되어 가족을 기근에서 구했다.', ref:'창세기 37~50장' , en:'Joseph', origin:'יוֹסֵף', pron:'요세프' },
  '유다': { category:'인물', desc:'야곱의 넷째 아들. 유다 지파의 조상이며 다윗과 예수의 계보를 이었다.', ref:'창세기 29장, 49장' , en:'Judah', origin:'יְהוּדָה', pron:'예후다' },
  '베냐민': { category:'인물', desc:'야곱의 막내아들. 베냐민 지파의 조상.', ref:'창세기 35장 이하' , en:'Benjamin', origin:'בִּנְיָמִין', pron:'빈야민' },
  '모세': { category:'인물', desc:'이스라엘을 애굽에서 이끌어낸 지도자이자 율법을 받은 사람. 십계명과 율법을 전했다.', ref:'출애굽기~신명기' , en:'Moses', origin:'מֹשֶׁה', pron:'모셰' },
  '아론': { category:'인물', desc:'모세의 형이자 최초의 대제사장. 모세의 대변인 역할을 했다.', ref:'출애굽기 4장 이하' , en:'Aaron', origin:'אַהֲרֹן', pron:'아하론' },
  '미리암': { category:'인물', desc:'모세와 아론의 누이. 홍해를 건넌 뒤 찬양을 인도한 여선지자.', ref:'출애굽기 15장' , en:'Miriam', origin:'מִרְיָם', pron:'미르얌' },
  '여호수아': { category:'인물', desc:'모세의 후계자로 이스라엘을 이끌고 가나안 땅에 들어가 정복했다.', ref:'여호수아서' , en:'Joshua', origin:'יְהוֹשֻׁעַ', pron:'예호슈아' },
  '갈렙': { category:'인물', desc:'가나안을 정탐한 열두 정탐꾼 중 믿음으로 보고한 두 사람 중 하나.', ref:'민수기 13~14장' , en:'Caleb', origin:'כָּלֵב', pron:'칼레브' },
  '발람': { category:'인물', desc:'이스라엘을 저주하려다 도리어 축복한 이방 선지자.', ref:'민수기 22~24장' , en:'Balaam', origin:'בִּלְעָם', pron:'빌암' },
  '라합': { category:'인물', desc:'여리고의 기생으로 정탐꾼을 숨겨줘 구원받았고 예수의 족보에 올랐다.', ref:'여호수아 2장' , en:'Rahab', origin:'רָחָב', pron:'라하브' },
  '기드온': { category:'인물', desc:'300명으로 미디안을 물리친 사사.', ref:'사사기 6~8장' , en:'Gideon', origin:'גִּדְעוֹן', pron:'기드온' },
  '삼손': { category:'인물', desc:'나실인으로 큰 힘을 지닌 사사. 들릴라에게 비밀을 빼앗겼다.', ref:'사사기 13~16장' , en:'Samson', origin:'שִׁמְשׁוֹן', pron:'쉼숀' },
  '드보라': { category:'인물', desc:'이스라엘을 이끈 여사사이자 선지자.', ref:'사사기 4~5장' , en:'Deborah', origin:'דְּבוֹרָה', pron:'데보라' },
  '룻': { category:'인물', desc:'모압 여인으로 시어머니 나오미를 따라와 보아스와 결혼, 다윗의 증조모가 되었다.', ref:'룻기' , en:'Ruth', origin:'רוּת', pron:'루트' },
  '나오미': { category:'인물', desc:'룻의 시어머니. 모압에서 남편과 두 아들을 잃고 베들레헴으로 돌아왔다.', ref:'룻기' , en:'Naomi', origin:'נָעֳמִי', pron:'나오미' },
  '보아스': { category:'인물', desc:'룻의 남편이자 다윗의 증조부. 기업 무를 자(고엘) 역할을 했다.', ref:'룻기' , en:'Boaz', origin:'בֹּעַז', pron:'보아즈' },
  '한나': { category:'인물', desc:'사무엘의 어머니. 기도로 얻은 아들을 하나님께 바쳤다.', ref:'사무엘상 1~2장' , en:'Hannah', origin:'חַנָּה', pron:'한나' },
  '사무엘': { category:'인물', desc:'마지막 사사이자 선지자. 사울과 다윗에게 기름을 부어 왕으로 세웠다.', ref:'사무엘상' , en:'Samuel', origin:'שְׁמוּאֵל', pron:'셰무엘' },
  '사울': { category:'인물', desc:'이스라엘의 첫 번째 왕. 처음엔 겸손했으나 불순종으로 버림받았다.', ref:'사무엘상 9장 이하' , en:'Saul', origin:'שָׁאוּל', pron:'샤울' },
  '다윗': { category:'인물', desc:'이스라엘의 두 번째 왕. 골리앗을 이긴 목동 출신으로 시편을 많이 지었고 메시아의 조상이 되었다.', ref:'사무엘상 16장 이하' , en:'David', origin:'דָּוִד', pron:'다비드' },
  '요나단': { category:'인물', desc:'사울의 아들이자 다윗의 신실한 친구.', ref:'사무엘상 18~20장' , en:'Jonathan', origin:'יְהוֹנָתָן', pron:'예호나탄' },
  '골리앗': { category:'인물', desc:'다윗이 물맷돌로 쓰러뜨린 블레셋의 거인 장수.', ref:'사무엘상 17장' , en:'Goliath', origin:'גָּלְיָת', pron:'골야트' },
  '밧세바': { category:'인물', desc:'다윗이 범죄해 아내로 삼은 여인. 솔로몬의 어머니.', ref:'사무엘하 11~12장' , en:'Bathsheba', origin:'בַּת־שֶׁבַע', pron:'바트셰바' },
  '나단': { category:'인물', desc:'다윗의 죄를 책망한 선지자.', ref:'사무엘하 12장' , en:'Nathan', origin:'נָתָן', pron:'나탄' },
  '압살롬': { category:'인물', desc:'다윗의 아들로 반역을 일으켰다가 죽었다.', ref:'사무엘하 15~18장' , en:'Absalom', origin:'אַבְשָׁלוֹם', pron:'아브샬롬' },
  '솔로몬': { category:'인물', desc:'다윗의 아들로 지혜로운 왕. 예루살렘 성전을 건축했다.', ref:'열왕기상 1~11장' , en:'Solomon', origin:'שְׁלֹמֹה', pron:'셸로모' },
  '르호보암': { category:'인물', desc:'솔로몬의 아들. 그의 폭정으로 나라가 남북으로 분열되었다.', ref:'열왕기상 12장' , en:'Rehoboam', origin:'רְחַבְעָם', pron:'레하브암' },
  '여로보암': { category:'인물', desc:'북이스라엘의 첫 왕. 금송아지 우상을 세웠다.', ref:'열왕기상 12~14장' , en:'Jeroboam', origin:'יָרָבְעָם', pron:'야로브암' },
  '엘리야': { category:'인물', desc:'아합 시대의 선지자. 갈멜산에서 바알 선지자와 대결했고 회오리바람으로 하늘에 올라갔다.', ref:'열왕기상 17장~열왕기하 2장' , en:'Elijah', origin:'אֵלִיָּהוּ', pron:'엘리야후' },
  '엘리사': { category:'인물', desc:'엘리야의 뒤를 이은 선지자. 많은 기적을 행했다.', ref:'열왕기하 2장 이하' , en:'Elisha', origin:'אֱלִישָׁע', pron:'엘리샤' },
  '아합': { category:'인물', desc:'북이스라엘의 악한 왕. 이세벨과 함께 바알을 섬겼다.', ref:'열왕기상 16~22장' , en:'Ahab', origin:'אַחְאָב', pron:'아흐아브' },
  '이세벨': { category:'인물', desc:'아합의 아내로 바알 숭배를 퍼뜨린 악한 왕비.', ref:'열왕기상 16장 이하' , en:'Jezebel', origin:'אִיזֶבֶל', pron:'이제벨' },
  '히스기야': { category:'인물', desc:'유다의 경건한 왕. 종교 개혁을 하고 앗수르의 침략에서 구원받았다.', ref:'열왕기하 18~20장' , en:'Hezekiah', origin:'חִזְקִיָּהוּ', pron:'히즈키야후' },
  '요시야': { category:'인물', desc:'어린 나이에 왕이 되어 율법책을 발견하고 대대적 개혁을 한 유다 왕.', ref:'열왕기하 22~23장' , en:'Josiah', origin:'יֹאשִׁיָּהוּ', pron:'요쉬야후' },
  '느부갓네살': { category:'인물', desc:'유다를 멸망시키고 포로로 끌고 간 바벨론의 왕.', ref:'열왕기하 24~25장, 다니엘' , en:'Nebuchadnezzar', origin:'נְבוּכַדְנֶאצַּר', pron:'네부카드네차르' },
  '이사야': { category:'인물', desc:'메시아를 예언한 대선지자.', ref:'이사야서' , en:'Isaiah', origin:'יְשַׁעְיָהוּ', pron:'예샤야후' },
  '예레미야': { category:'인물', desc:'유다 멸망을 눈물로 예언한 선지자.', ref:'예레미야서' , en:'Jeremiah', origin:'יִרְמְיָהוּ', pron:'이르메야후' },
  '에스겔': { category:'인물', desc:'바벨론 포로 중에 환상을 본 선지자.', ref:'에스겔서' , en:'Ezekiel', origin:'יְחֶזְקֵאל', pron:'예헤즈켈' },
  '다니엘': { category:'인물', desc:'바벨론 포로로 끌려가 사자굴에서도 신앙을 지킨 선지자.', ref:'다니엘서' , en:'Daniel', origin:'דָּנִיֵּאל', pron:'다니엘' },
  '호세아': { category:'인물', desc:'이스라엘의 영적 간음을 자신의 결혼으로 보여준 선지자.', ref:'호세아서' , en:'Hosea', origin:'הוֹשֵׁעַ', pron:'호셰아' },
  '요나': { category:'인물', desc:'니느웨로 보내심을 받았으나 도망치다 큰 물고기 뱃속에 들어간 선지자.', ref:'요나서' , en:'Jonah', origin:'יוֹנָה', pron:'요나' },
  '느헤미야': { category:'인물', desc:'포로 귀환 후 예루살렘 성벽을 재건한 지도자.', ref:'느헤미야서' , en:'Nehemiah', origin:'נְחֶמְיָה', pron:'네헤므야' },
  '에스라': { category:'인물', desc:'포로 귀환 후 율법을 가르친 학사이자 제사장.', ref:'에스라서' , en:'Ezra', origin:'עֶזְרָא', pron:'에즈라' },
  '에스더': { category:'인물', desc:'페르시아 왕비가 되어 동족 유대인을 멸절 위기에서 구한 여인.', ref:'에스더서' , en:'Esther', origin:'אֶסְתֵּר', pron:'에스테르' },
  '모르드개': { category:'인물', desc:'에스더의 사촌오빠로 유대인을 구하는 데 앞장섰다.', ref:'에스더서' , en:'Mordecai', origin:'מָרְדֳּכַי', pron:'모르도카이' },
  '욥': { category:'인물', desc:'큰 고난 가운데서도 하나님을 향한 믿음을 지킨 의인.', ref:'욥기' , en:'Job', origin:'אִיּוֹב', pron:'이요브' },
  '예수': { category:'인물', desc:'하나님의 아들이자 구원자 그리스도. 인류의 죄를 위해 십자가에서 죽고 부활하셨다.', ref:'사복음서' , en:'Jesus', origin:'Ἰησοῦς', pron:'이에수스' },
  '마리아': { category:'인물', desc:'성령으로 예수를 잉태해 낳은 동정녀 어머니.', ref:'마태복음 1장, 누가복음 1~2장' , en:'Mary', origin:'Μαρία', pron:'마리아' },
  '요셉(신약)': { category:'인물', desc:'마리아의 남편이자 예수의 양육자. 다윗의 후손인 목수.', ref:'마태복음 1~2장' , en:'Joseph', origin:'Ἰωσήφ', pron:'이오세프' },
  '세례요한': { category:'인물', desc:'예수의 길을 예비한 선지자. 요단강에서 회개의 세례를 베풀었다.', ref:'마태복음 3장 등' , en:'John the Baptist', origin:'Ἰωάννης ὁ βαπτιστής', pron:'이오안네스' },
  '베드로': { category:'인물', desc:'예수의 수제자. 본명은 시몬. 초대교회의 지도자가 되었다.', ref:'사복음서, 사도행전' , en:'Peter', origin:'Πέτρος', pron:'페트로스' },
  '안드레': { category:'인물', desc:'베드로의 동생이자 예수의 제자. 처음으로 예수를 따랐다.', ref:'요한복음 1장 등' , en:'Andrew', origin:'Ἀνδρέας', pron:'안드레아스' },
  '야고보': { category:'인물', desc:'세베대의 아들이자 요한의 형. 예수의 핵심 제자 중 하나.', ref:'사복음서' , en:'James', origin:'Ἰάκωβος', pron:'이아코보스' },
  '요한': { category:'인물', desc:'예수의 사랑받은 제자. 요한복음과 요한계시록의 저자로 전해진다.', ref:'요한복음 등' , en:'John', origin:'Ἰωάννης', pron:'이오안네스' },
  '빌립': { category:'인물', desc:'예수의 열두 제자 중 하나.', ref:'요한복음 1장, 6장' , en:'Philip', origin:'Φίλιππος', pron:'필립포스' },
  '도마': { category:'인물', desc:'예수의 부활을 의심하다 직접 보고 믿은 제자.', ref:'요한복음 20장' , en:'Thomas', origin:'Θωμᾶς', pron:'토마스' },
  '마태': { category:'인물', desc:'세리 출신의 예수 제자. 마태복음의 저자로 전해진다.', ref:'마태복음 9장' , en:'Matthew', origin:'Ματθαῖος', pron:'맛타이오스' },
  '가룟유다': { category:'인물', desc:'예수를 은 삼십에 판 배신자 제자.', ref:'마태복음 26~27장' , en:'Judas Iscariot', origin:'Ἰούδας', pron:'이우다스' },
  '막달라마리아': { category:'인물', desc:'예수께 고침받고 부활을 처음 목격한 여인.', ref:'요한복음 20장 등' , en:'Mary Magdalene', origin:'Μαρία ἡ Μαγδαληνή', pron:'마리아' },
  '나사로': { category:'인물', desc:'예수께서 죽은 지 나흘 만에 살리신 베다니 사람.', ref:'요한복음 11장' , en:'Lazarus', origin:'Λάζαρος', pron:'라자로스' },
  '마르다': { category:'인물', desc:'나사로와 마리아의 자매. 예수를 섬긴 베다니의 여인.', ref:'누가복음 10장, 요한복음 11장' , en:'Martha', origin:'Μάρθα', pron:'마르타' },
  '니고데모': { category:'인물', desc:'밤에 예수를 찾아온 바리새인이자 산헤드린 의원.', ref:'요한복음 3장' , en:'Nicodemus', origin:'Νικόδημος', pron:'니코데모스' },
  '바디매오': { category:'인물', desc:'예수께 고침받은 여리고의 맹인 거지.', ref:'마가복음 10장' , en:'Bartimaeus', origin:'Βαρτιμαῖος', pron:'바르티마이오스' },
  '삭개오': { category:'인물', desc:'예수를 만나 변화된 여리고의 세리장.', ref:'누가복음 19장' , en:'Zacchaeus', origin:'Ζακχαῖος', pron:'자카이오스' },
  '빌라도': { category:'인물', desc:'예수에게 십자가형을 선고한 로마 총독.', ref:'사복음서' , en:'Pilate', origin:'Πιλᾶτος', pron:'필라토스' },
  '헤롯': { category:'인물', desc:'예수 탄생 무렵 유아 학살을 명한 분봉왕 가문의 통치자.', ref:'마태복음 2장 등' , en:'Herod', origin:'Ἡρῴδης', pron:'헤로데스' },
  '가야바': { category:'인물', desc:'예수를 심문한 당시 대제사장.', ref:'마태복음 26장' , en:'Caiaphas', origin:'Καϊάφας', pron:'카이아파스' },
  '스데반': { category:'인물', desc:'최초의 순교자. 일곱 집사 중 하나로 돌에 맞아 죽었다.', ref:'사도행전 6~7장' , en:'Stephen', origin:'Στέφανος', pron:'스테파노스' },
  '바울': { category:'인물', desc:'교회를 박해하다 회심해 이방인의 사도가 된 인물. 본명은 사울.', ref:'사도행전, 서신서' , en:'Paul', origin:'Παῦλος', pron:'파울로스' },
  '바나바': { category:'인물', desc:'바울의 동역자로 권위와 위로의 사람. 1차 전도여행을 함께했다.', ref:'사도행전 11~15장' , en:'Barnabas', origin:'Βαρναβᾶς', pron:'바르나바스' },
  '실라': { category:'인물', desc:'바울의 2차 전도여행 동역자.', ref:'사도행전 15~18장' , en:'Silas', origin:'Σίλας', pron:'실라스' },
  '디모데': { category:'인물', desc:'바울의 영적 아들이자 동역자. 에베소 교회를 섬겼다.', ref:'디모데전후서' , en:'Timothy', origin:'Τιμόθεος', pron:'티모테오스' },
  '디도': { category:'인물', desc:'바울의 동역자로 그레데 교회를 돌본 일꾼.', ref:'디도서' , en:'Titus', origin:'Τίτος', pron:'티토스' },
  '누가': { category:'인물', desc:'의사이자 누가복음·사도행전의 저자. 바울의 동행자.', ref:'누가복음, 사도행전' , en:'Luke', origin:'Λουκᾶς', pron:'루카스' },
  '마가': { category:'인물', desc:'마가복음의 저자. 바나바의 조카.', ref:'사도행전, 마가복음' , en:'Mark', origin:'Μᾶρκος', pron:'마르코스' },
  '아볼로': { category:'인물', desc:'성경에 능통한 알렉산드리아 출신 전도자.', ref:'사도행전 18장' , en:'Apollos', origin:'Ἀπολλῶς', pron:'아폴로스' },
  '브리스길라': { category:'인물', desc:'아굴라의 아내로 바울의 동역자. 아볼로를 가르쳤다.', ref:'사도행전 18장' , en:'Priscilla', origin:'Πρίσκιλλα', pron:'프리스킬라' },
  '아굴라': { category:'인물', desc:'브리스길라의 남편이자 천막 만드는 바울의 동역자.', ref:'사도행전 18장' , en:'Aquila', origin:'Ἀκύλας', pron:'아킬라스' },
  '루디아': { category:'인물', desc:'빌립보에서 회심한 자색 옷감 장수. 유럽 최초의 신자.', ref:'사도행전 16장' , en:'Lydia', origin:'Λυδία', pron:'리디아' },
  '고넬료': { category:'인물', desc:'베드로를 통해 복음을 들은 로마 백부장. 첫 이방인 신자.', ref:'사도행전 10장' , en:'Cornelius', origin:'Κορνήλιος', pron:'코르넬리오스' },
  '아간': { category:'인물', desc:'여리고 정복 후 금지된 물건을 훔쳐 이스라엘에 패배를 부른 자.', ref:'여호수아 7장' , en:'Achan', origin:'עָכָן', pron:'아칸' },
  '옷니엘': { category:'인물', desc:'이스라엘의 첫 사사. 갈렙의 조카.', ref:'사사기 3장' , en:'Othniel', origin:'עָתְנִיאֵל', pron:'오트니엘' },
  '에훗': { category:'인물', desc:'왼손잡이 사사로 모압 왕 에글론을 처치했다.', ref:'사사기 3장' , en:'Ehud', origin:'אֵהוּד', pron:'에후드' },
  '바락': { category:'인물', desc:'드보라와 함께 가나안 군대를 무찌른 장수.', ref:'사사기 4장' , en:'Barak', origin:'בָּרָק', pron:'바라크' },
  '입다': { category:'인물', desc:'경솔한 서원으로 딸을 잃은 사사.', ref:'사사기 11장' , en:'Jephthah', origin:'יִפְתָּח', pron:'이프타흐' },
  '엘리': { category:'인물', desc:'사무엘을 양육한 제사장. 두 아들의 악행으로 심판받았다.', ref:'사무엘상 1~4장' , en:'Eli', origin:'עֵלִי', pron:'엘리' },
  '아비가일': { category:'인물', desc:'지혜로 다윗의 보복을 막고 후에 그의 아내가 된 여인.', ref:'사무엘상 25장' , en:'Abigail', origin:'אֲבִיגַיִל', pron:'아비가일' },
  '요압': { category:'인물', desc:'다윗의 군대장관.', ref:'사무엘하' , en:'Joab', origin:'יוֹאָב', pron:'요아브' },
  '아비새': { category:'인물', desc:'다윗의 용사이자 요압의 형제.', ref:'사무엘하' , en:'Abishai', origin:'אֲבִישַׁי', pron:'아비샤이' },
  '므비보셋': { category:'인물', desc:'요나단의 아들로 다윗의 은혜를 입은 절뚝발이.', ref:'사무엘하 9장' , en:'Mephibosheth', origin:'מְפִיבֹשֶׁת', pron:'메피보셰트' },
  '아도니야': { category:'인물', desc:'솔로몬에 앞서 스스로 왕이 되려 한 다윗의 아들.', ref:'열왕기상 1장' , en:'Adonijah', origin:'אֲדֹנִיָּה', pron:'아도니야' },
  '나봇': { category:'인물', desc:'아합에게 포도원을 빼앗기고 죽임당한 의인.', ref:'열왕기상 21장' , en:'Naboth', origin:'נָבוֹת', pron:'나보트' },
  '엘리사벳': { category:'인물', desc:'세례 요한의 어머니이자 마리아의 친족.', ref:'누가복음 1장' , en:'Elizabeth', origin:'Ἐλισάβετ', pron:'엘리사벳' },
  '스가랴': { category:'인물', desc:'세례 요한의 아버지인 제사장.', ref:'누가복음 1장' , en:'Zechariah', origin:'זְכַרְיָה', pron:'제카르야' },
  '시므온': { category:'인물', desc:'성전에서 아기 예수를 보고 찬송한 경건한 노인.', ref:'누가복음 2장' , en:'Simeon', origin:'Συμεών', pron:'쉬메온' },
  '안나': { category:'인물', desc:'성전에서 예수를 보고 증언한 여선지자.', ref:'누가복음 2장' , en:'Anna', origin:'Ἅννα', pron:'안나' },
  '아모스': { category:'인물', desc:'공의를 외친 목자 출신 선지자.', ref:'아모스서' , en:'Amos', origin:'עָמוֹס', pron:'아모스' },
  '미가': { category:'인물', desc:'베들레헴에서 메시아가 나실 것을 예언한 선지자.', ref:'미가서' , en:'Micah', origin:'מִיכָה', pron:'미카' },
  '스바냐': { category:'인물', desc:'여호와의 날을 예언한 선지자.', ref:'스바냐서' , en:'Zephaniah', origin:'צְפַנְיָה', pron:'체판야' },
  '학개': { category:'인물', desc:'성전 재건을 독려한 포로 귀환기 선지자.', ref:'학개서' , en:'Haggai', origin:'חַגַּי', pron:'하가이' },
  '스가랴(선지자)': { category:'인물', desc:'성전 재건과 메시아를 예언한 포로 귀환기 선지자.', ref:'스가랴서' , en:'Zechariah', origin:'זְכַרְיָה', pron:'제카르야' },
  '말라기': { category:'인물', desc:'구약의 마지막 선지자.', ref:'말라기서' , en:'Malachi', origin:'מַלְאָכִי', pron:'말아키' },
  '요엘': { category:'인물', desc:'성령 강림을 예언한 선지자.', ref:'요엘서' , en:'Joel', origin:'יוֹאֵל', pron:'요엘' },
  '오바댜': { category:'인물', desc:'에돔의 심판을 예언한 가장 짧은 예언서의 선지자.', ref:'오바댜서' , en:'Obadiah', origin:'עֹבַדְיָה', pron:'오바드야' },
  '나훔': { category:'인물', desc:'니느웨의 멸망을 예언한 선지자.', ref:'나훔서' , en:'Nahum', origin:'נַחוּם', pron:'나훔' },
  '하박국': { category:'인물', desc:'악인의 형통을 두고 하나님과 대화한 선지자.', ref:'하박국서' , en:'Habakkuk', origin:'חֲבַקּוּק', pron:'하바쿠크' },
  '나아만': { category:'인물', desc:'엘리사를 통해 나병이 나은 아람의 장군.', ref:'열왕기하 5장' , en:'Naaman', origin:'נַעֲמָן', pron:'나아만' },
  '게하시': { category:'인물', desc:'엘리사의 종으로 욕심 때문에 나병에 걸렸다.', ref:'열왕기하 5장' , en:'Gehazi', origin:'גֵּיחֲזִי', pron:'게하지' },
  '요시아': { category:'인물', desc:'유다의 개혁 군주(요시야의 표기 변형).', ref:'열왕기하 22장' , en:'Josiah', origin:'יֹאשִׁיָּהוּ', pron:'요쉬야후' },
  '글로바': { category:'인물', desc:'엠마오로 가던 두 제자 중 하나.', ref:'누가복음 24장' , en:'Cleopas', origin:'Κλεοπᾶς', pron:'클레오파스' },
  '마리아(베다니)': { category:'인물', desc:'예수의 발에 향유를 부은 나사로의 누이.', ref:'요한복음 12장' , en:'Mary of Bethany', origin:'Μαρία', pron:'마리아' },
  '살로메': { category:'인물', desc:'세베대 아들들의 어머니로 예수를 따른 여인.', ref:'마가복음 15장' , en:'Salome', origin:'Σαλώμη', pron:'살로메' },
  '아나니아': { category:'인물', desc:'바울에게 안수해 눈을 뜨게 한 다메섹 제자.', ref:'사도행전 9장' , en:'Ananias', origin:'Ἁνανίας', pron:'하나니아스' },
  '빌레몬': { category:'인물', desc:'바울이 도망친 종 오네시모를 위해 편지를 보낸 사람.', ref:'빌레몬서' , en:'Philemon', origin:'Φιλήμων', pron:'필레몬' },
  '오네시모': { category:'인물', desc:'빌레몬에게서 도망쳤다가 바울을 통해 회심한 종.', ref:'빌레몬서' , en:'Onesimus', origin:'Ὀνήσιμος', pron:'오네시모스' },
  '디모데전후서의 디모데': { category:'인물', desc:'바울이 목회 서신을 보낸 젊은 목회자.', ref:'디모데전후서' , en:'Timothy', origin:'Τιμόθεος', pron:'티모테오스' },
  '아가보': { category:'인물', desc:'흉년과 바울의 결박을 예언한 선지자.', ref:'사도행전 11장, 21장' , en:'Agabus', origin:'Ἅγαβος', pron:'하가보스' },
  '유니아': { category:'인물', desc:'바울이 사도들에게 존중받는다고 인사한 인물.', ref:'로마서 16장' , en:'Junia', origin:'Ἰουνία', pron:'이우니아' },
  '뵈뵈': { category:'인물', desc:'겐그레아 교회의 여집사로 로마서를 전달한 것으로 여겨진다.', ref:'로마서 16장' , en:'Phoebe', origin:'Φοίβη', pron:'포이베' },
  '데마': { category:'인물', desc:'한때 바울과 동역했으나 세상을 사랑해 떠난 사람.', ref:'디모데후서 4장' , en:'Demas', origin:'Δημᾶς', pron:'데마스' },
  '두기고': { category:'인물', desc:'바울의 편지를 전한 신실한 일꾼.', ref:'에베소서 6장' , en:'Tychicus', origin:'Τυχικός', pron:'튀키코스' },
  '에바브라': { category:'인물', desc:'골로새 교회를 섬긴 바울의 동역자.', ref:'골로새서' , en:'Epaphras', origin:'Ἐπαφρᾶς', pron:'에파프라스' },
  '실루아노': { category:'인물', desc:'실라의 다른 이름. 바울·베드로의 동역자.', ref:'베드로전서 5장' , en:'Silvanus', origin:'Σιλουανός', pron:'실루아노스' },

  // ── 지명 ──
  '에덴': { category:'지명', desc:'하나님이 아담과 하와를 두신 동산. 풍요롭고 평화로운 낙원.', ref:'창세기 2장' , en:'Eden', origin:'עֵדֶן', pron:'에덴' },
  '아라랏': { category:'지명', desc:'노아의 방주가 머문 산.', ref:'창세기 8장' , en:'Ararat', origin:'אֲרָרָט', pron:'아라라트' },
  '바벨': { category:'지명', desc:'사람들이 하늘에 닿는 탑을 쌓다 언어가 혼잡해진 곳.', ref:'창세기 11장' , en:'Babel', origin:'בָּבֶל', pron:'바벨' },
  '우르': { category:'지명', desc:'아브라함이 부르심을 받기 전 살던 갈대아 지역의 성읍.', ref:'창세기 11장' , en:'Ur', origin:'אוּר', pron:'우르' },
  '가나안': { category:'지명', desc:'하나님이 아브라함과 그 자손에게 약속하신 땅. 오늘날 팔레스타인 지역.', ref:'창세기 12장 이하' , en:'Canaan', origin:'כְּנַעַן', pron:'케나안' },
  '소돔': { category:'지명', desc:'죄악으로 멸망당한 성. 고모라와 함께 불 심판을 받았다.', ref:'창세기 18~19장' , en:'Sodom', origin:'סְדֹם', pron:'세돔' },
  '고모라': { category:'지명', desc:'소돔과 함께 죄악으로 불 심판을 받은 성.', ref:'창세기 18~19장' , en:'Gomorrah', origin:'עֲמֹרָה', pron:'아모라' },
  '애굽': { category:'지명', desc:'이집트의 옛 이름. 이스라엘이 종살이하다 모세를 통해 탈출한 곳.', ref:'출애굽기' , en:'Egypt', origin:'מִצְרַיִם', pron:'미츠라임' },
  '홍해': { category:'지명', desc:'모세가 지팡이를 들자 갈라져 이스라엘이 건넌 바다.', ref:'출애굽기 14장' , en:'Red Sea', origin:'יַם סוּף', pron:'얌 수프' },
  '시내산': { category:'지명', desc:'모세가 십계명과 율법을 받은 산. 호렙산이라고도 한다.', ref:'출애굽기 19~20장' , en:'Mount Sinai', origin:'הַר סִינַי', pron:'하르 시나이' },
  '광야': { category:'지명', desc:'이스라엘이 출애굽 후 40년간 유랑한 메마른 땅.', ref:'출애굽기~신명기' , en:'Wilderness', origin:'מִדְבָּר', pron:'미드바르' },
  '요단강': { category:'지명', desc:'이스라엘이 건너 가나안에 들어간 강. 예수도 여기서 세례받았다.', ref:'여호수아 3장, 마태복음 3장' , en:'Jordan River', origin:'יַרְדֵּן', pron:'야르덴' },
  '여리고': { category:'지명', desc:'가나안 정복 때 성벽이 무너진 첫 성.', ref:'여호수아 6장' , en:'Jericho', origin:'יְרִיחוֹ', pron:'예리호' },
  '실로': { category:'지명', desc:'가나안 정착 초기 성막이 있던 중심지.', ref:'여호수아 18장, 사무엘상 1장' , en:'Shiloh', origin:'שִׁילֹה', pron:'쉴로' },
  '예루살렘': { category:'지명', desc:'다윗이 수도로 삼은 이스라엘의 중심 도시. 성전이 있던 거룩한 성.', ref:'사무엘하 5장 이하' , en:'Jerusalem', origin:'יְרוּשָׁלַיִם', pron:'예루샬라임' },
  '시온': { category:'지명', desc:'예루살렘의 다른 이름이자 하나님의 거룩한 산을 가리키는 상징.', ref:'시편 등' , en:'Zion', origin:'צִיּוֹן', pron:'치욘' },
  '베들레헴': { category:'지명', desc:'다윗의 고향이자 예수가 태어난 마을. 떡집이라는 뜻.', ref:'미가 5:2, 누가복음 2장' , en:'Bethlehem', origin:'בֵּית לֶחֶם', pron:'베이트 레헴' },
  '헤브론': { category:'지명', desc:'아브라함이 머물고 묻힌 곳. 다윗이 처음 왕이 된 성읍.', ref:'창세기 23장, 사무엘하 5장' , en:'Hebron', origin:'חֶבְרוֹן', pron:'헤브론' },
  '브엘세바': { category:'지명', desc:'아브라함과 이삭이 우물을 판 남방의 성읍.', ref:'창세기 21장, 26장' , en:'Beersheba', origin:'בְּאֵר שֶׁבַע', pron:'베에르 셰바' },
  '벧엘': { category:'지명', desc:'야곱이 사닥다리 환상을 본 곳. 하나님의 집이라는 뜻.', ref:'창세기 28장' , en:'Bethel', origin:'בֵּית אֵל', pron:'베이트 엘' },
  '사마리아': { category:'지명', desc:'북이스라엘의 수도. 신약 시대 유대인과 사이가 나빴던 지역.', ref:'열왕기상 16장, 요한복음 4장' , en:'Samaria', origin:'שֹׁמְרוֹן', pron:'쇼므론' },
  '갈릴리': { category:'지명', desc:'예수가 주로 사역한 북부 지역. 갈릴리 호수가 있다.', ref:'사복음서' , en:'Galilee', origin:'Γαλιλαία', pron:'갈릴라이아' },
  '나사렛': { category:'지명', desc:'예수가 자란 갈릴리의 마을.', ref:'누가복음 2장' , en:'Nazareth', origin:'Ναζαρέθ', pron:'나자레트' },
  '가버나움': { category:'지명', desc:'예수가 갈릴리 사역의 본거지로 삼은 호숫가 마을.', ref:'마태복음 4장 등' , en:'Capernaum', origin:'Καφαρναούμ', pron:'카파르나움' },
  '감람산': { category:'지명', desc:'예수가 기도하고 승천하신 예루살렘 동쪽 산. 올리브산.', ref:'마태복음 24장, 사도행전 1장' , en:'Mount of Olives', origin:'Ὄρος τῶν Ἐλαιῶν', pron:'올리브산' },
  '겟세마네': { category:'지명', desc:'예수가 잡히시기 전 피땀 흘려 기도한 동산.', ref:'마태복음 26장' , en:'Gethsemane', origin:'Γεθσημανῆ', pron:'겟세마네' },
  '골고다': { category:'지명', desc:'예수가 십자가에 못 박히신 곳. 해골이라는 뜻.', ref:'마태복음 27장' , en:'Golgotha', origin:'Γολγοθᾶ', pron:'골고타' },
  '베다니': { category:'지명', desc:'나사로·마르다·마리아가 살던 예루살렘 근처 마을.', ref:'요한복음 11장' , en:'Bethany', origin:'Βηθανία', pron:'베타니아' },
  '다메섹': { category:'지명', desc:'바울이 회심한 시리아의 도시. 다마스쿠스.', ref:'사도행전 9장' , en:'Damascus', origin:'Δαμασκός', pron:'다마스코스' },
  '안디옥': { category:'지명', desc:'제자들이 처음으로 그리스도인이라 불린 도시. 바울 선교의 거점.', ref:'사도행전 11장' , en:'Antioch', origin:'Ἀντιόχεια', pron:'안티오케이아' },
  '고린도': { category:'지명', desc:'바울이 교회를 세운 그리스의 항구 도시.', ref:'사도행전 18장, 고린도전후서' , en:'Corinth', origin:'Κόρινθος', pron:'코린토스' },
  '에베소': { category:'지명', desc:'바울이 오래 사역한 소아시아의 대도시.', ref:'사도행전 19장, 에베소서' , en:'Ephesus', origin:'Ἔφεσος', pron:'에페소스' },
  '빌립보': { category:'지명', desc:'유럽 최초의 교회가 세워진 마케도니아의 도시.', ref:'사도행전 16장, 빌립보서' , en:'Philippi', origin:'Φίλιπποι', pron:'필립포이' },
  '로마': { category:'지명', desc:'당시 세계의 중심 제국의 수도. 바울이 복음을 전한 목표지.', ref:'사도행전 28장, 로마서' , en:'Rome', origin:'Ῥώμη', pron:'로메' },
  '앗수르': { category:'지명', desc:'북이스라엘을 멸망시킨 고대 제국. 아시리아.', ref:'열왕기하 17장' , en:'Assyria', origin:'אַשּׁוּר', pron:'아슈르' },
  '바벨론': { category:'지명', desc:'유다를 멸망시키고 백성을 포로로 끌고 간 고대 제국.', ref:'열왕기하 24~25장' , en:'Babylon', origin:'בָּבֶל', pron:'바벨' },
  '니느웨': { category:'지명', desc:'요나가 회개를 전한 앗수르의 큰 성.', ref:'요나서' , en:'Nineveh', origin:'נִינְוֵה', pron:'니느베' },
  '밧모': { category:'지명', desc:'사도 요한이 유배되어 계시록을 기록한 섬.', ref:'요한계시록 1장' , en:'Patmos', origin:'Πάτμος', pron:'파트모스' },
  '미디안': { category:'지명', desc:'모세가 도피해 머문 광야 지역. 이드로의 땅.', ref:'출애굽기 2~3장' , en:'Midian', origin:'מִדְיָן', pron:'미드얀' },
  '모압': { category:'지명', desc:'롯의 후손이 이룬 사해 동편의 나라. 룻의 고향.', ref:'룻기, 민수기' , en:'Moab', origin:'מוֹאָב', pron:'모아브' },
  '에돔': { category:'지명', desc:'에서의 후손이 사는 사해 남쪽 지역.', ref:'창세기 36장' , en:'Edom', origin:'אֱדוֹם', pron:'에돔' },
  '블레셋': { category:'지명', desc:'지중해 연안에 살던 이스라엘의 숙적. 골리앗의 민족.', ref:'사사기, 사무엘상' , en:'Philistia', origin:'פְּלֶשֶׁת', pron:'펠레셰트' },
  '길르앗': { category:'지명', desc:'요단 동편의 산악 지역. 향유로 유명했다.', ref:'창세기 37장, 예레미야 8장' , en:'Gilead', origin:'גִּלְעָד', pron:'길아드' },
  '갈멜산': { category:'지명', desc:'엘리야가 바알 선지자와 대결한 산.', ref:'열왕기상 18장' , en:'Mount Carmel', origin:'הַר הַכַּרְמֶל', pron:'하르 카르멜' },
  '호렙산': { category:'지명', desc:'시내산의 다른 이름. 하나님이 모세를 부르신 산.', ref:'출애굽기 3장' , en:'Mount Horeb', origin:'חֹרֵב', pron:'호레브' },
  '기손강': { category:'지명', desc:'드보라와 바락이 승리한 전장의 강.', ref:'사사기 4~5장' , en:'Kishon River', origin:'קִישׁוֹן', pron:'키숀' },
  '므깃도': { category:'지명', desc:'여러 전투가 벌어진 요충지. 아마겟돈의 어원.', ref:'사사기, 요한계시록 16장' , en:'Megiddo', origin:'מְגִדּוֹ', pron:'메기도' },
  '두로': { category:'지명', desc:'페니키아의 무역 항구 도시.', ref:'에스겔 26장, 마태복음 15장' , en:'Tyre', origin:'צֹר', pron:'초르' },
  '시돈': { category:'지명', desc:'두로와 함께한 페니키아의 항구 도시.', ref:'마태복음 15장' , en:'Sidon', origin:'צִידוֹן', pron:'치돈' },
  '가이사랴': { category:'지명', desc:'로마 총독부가 있던 지중해 항구. 고넬료의 도시.', ref:'사도행전 10장' , en:'Caesarea', origin:'Καισάρεια', pron:'카이사레이아' },
  '빌립보가이사랴': { category:'지명', desc:'베드로가 예수를 그리스도로 고백한 북부 지역.', ref:'마태복음 16장' , en:'Caesarea Philippi', origin:'Καισάρεια Φιλίππου', pron:'카이사레이아' },
  '데살로니가': { category:'지명', desc:'바울이 교회를 세운 마케도니아의 도시.', ref:'사도행전 17장, 데살로니가전후서' , en:'Thessalonica', origin:'Θεσσαλονίκη', pron:'테살로니케' },
  '베뢰아': { category:'지명', desc:'말씀을 날마다 상고한 신사적인 신자들의 도시.', ref:'사도행전 17장' , en:'Berea', origin:'Βέροια', pron:'베로이아' },
  '아덴': { category:'지명', desc:'바울이 철학자들과 변론한 그리스의 학문 도시. 아테네.', ref:'사도행전 17장' , en:'Athens', origin:'Ἀθῆναι', pron:'아테나이' },
  '아라비아': { category:'지명', desc:'바울이 회심 후 한동안 머문 지역.', ref:'갈라디아서 1장' , en:'Arabia', origin:'Ἀραβία', pron:'아라비아' },
  '그레데': { category:'지명', desc:'디도가 교회를 돌본 지중해의 섬. 크레타.', ref:'디도서' , en:'Crete', origin:'Κρήτη', pron:'크레테' },
  '골로새': { category:'지명', desc:'바울이 편지를 보낸 소아시아의 도시.', ref:'골로새서' , en:'Colossae', origin:'Κολοσσαί', pron:'콜롯사이' },
  '라오디게아': { category:'지명', desc:'계시록에서 미지근한 신앙으로 책망받은 교회의 도시.', ref:'요한계시록 3장' , en:'Laodicea', origin:'Λαοδίκεια', pron:'라오디케이아' },
  '서머나': { category:'지명', desc:'계시록의 일곱 교회 중 고난받는 교회의 도시.', ref:'요한계시록 2장' , en:'Smyrna', origin:'Σμύρνα', pron:'스뮈르나' },
  '버가모': { category:'지명', desc:'계시록의 일곱 교회 중 하나가 있던 도시.', ref:'요한계시록 2장' , en:'Pergamum', origin:'Πέργαμος', pron:'페르가모스' },
  '두아디라': { category:'지명', desc:'계시록의 일곱 교회 중 하나가 있던 도시.', ref:'요한계시록 2장' , en:'Thyatira', origin:'Θυάτειρα', pron:'튀아테이라' },
  '사데': { category:'지명', desc:'계시록의 일곱 교회 중 하나가 있던 도시.', ref:'요한계시록 3장' , en:'Sardis', origin:'Σάρδεις', pron:'사르데이스' },
  '빌라델비아': { category:'지명', desc:'계시록에서 칭찬받은 교회의 도시.', ref:'요한계시록 3장' , en:'Philadelphia', origin:'Φιλαδέλφεια', pron:'필라델페이아' },
  '구스': { category:'지명', desc:'애굽 남쪽의 지역. 에티오피아 일대.', ref:'이사야 18장' , en:'Cush', origin:'כּוּשׁ', pron:'쿠시' },

  // ── 용어 ──
  '여호와': { category:'용어', desc:'하나님의 언약적 이름. 스스로 있는 자라는 뜻으로 모세에게 계시된 거룩한 이름.', ref:'출애굽기 3:14' , en:'LORD / Yahweh', origin:'יְהוָה', pron:'야웨' },
  '엘로힘': { category:'용어', desc:'하나님을 가리키는 히브리어 이름. 창조주의 능력과 위엄을 나타낸다.', ref:'창세기 1장' , en:'God', origin:'אֱלֹהִים', pron:'엘로힘' },
  '메시아': { category:'용어', desc:'기름 부음 받은 자라는 뜻. 하나님이 보내실 구원자이며 헬라어로 그리스도.', ref:'다니엘 9장 등' , en:'Messiah', origin:'מָשִׁיחַ', pron:'마쉬아흐' },
  '그리스도': { category:'용어', desc:'메시아의 헬라어 표현. 기름 부음 받은 구원자, 곧 예수를 가리킨다.', ref:'마태복음 16장' , en:'Christ', origin:'Χριστός', pron:'크리스토스' },
  '임마누엘': { category:'용어', desc:'하나님이 우리와 함께 계시다라는 뜻. 예수의 별칭.', ref:'이사야 7:14, 마태복음 1:23' , en:'Immanuel', origin:'עִמָּנוּאֵל', pron:'임마누엘' },
  '바로': { category:'용어', desc:'고대 애굽 왕의 칭호. 특정 인물 이름이 아니라 왕을 가리키는 호칭.', ref:'창세기·출애굽기' , en:'Pharaoh', origin:'פַּרְעֹה', pron:'파르오' },
  '안식일': { category:'용어', desc:'이레째 날로 일을 쉬고 거룩하게 지키는 날. 천지창조 후 하나님이 쉬신 데서 비롯되었다.', ref:'창세기 2:2~3, 출애굽기 20장' , en:'Sabbath', origin:'שַׁבָּת', pron:'샤바트' },
  '안식년': { category:'용어', desc:'일곱째 해마다 땅을 쉬게 하고 빚을 면제하던 규례.', ref:'레위기 25장' , en:'Sabbath Year', origin:'שְׁמִטָּה', pron:'셰미타' },
  '희년': { category:'용어', desc:'오십 년째 되는 해로 노예 해방과 토지 반환이 이뤄진 회복의 해.', ref:'레위기 25장' , en:'Jubilee', origin:'יוֹבֵל', pron:'요벨' },
  '언약': { category:'용어', desc:'하나님과 사람 사이에 맺어진 약속. 노아·아브라함·모세·다윗 언약 등이 있다.', ref:'창세기 9장, 15장 등' , en:'Covenant', origin:'בְּרִית', pron:'베리트' },
  '율법': { category:'용어', desc:'하나님이 모세를 통해 주신 계명과 규례. 토라라고도 한다.', ref:'출애굽기~신명기' , en:'Law / Torah', origin:'תּוֹרָה', pron:'토라' },
  '십계명': { category:'용어', desc:'시내산에서 하나님이 주신 열 가지 핵심 계명.', ref:'출애굽기 20장' , en:'Ten Commandments', origin:'עֲשֶׂרֶת הַדְּבָרִים', pron:'아세레트 하데바림' },
  '토라': { category:'용어', desc:'구약의 첫 다섯 권(모세오경)을 가리키는 말. 가르침·율법이라는 뜻.', ref:'창세기~신명기' , en:'Torah', origin:'תּוֹרָה', pron:'토라' },
  '할례': { category:'용어', desc:'아브라함 언약의 표징으로 남자의 양피를 베는 의식.', ref:'창세기 17장' , en:'Circumcision', origin:'מִילָה', pron:'밀라' },
  '유월절': { category:'용어', desc:'애굽의 마지막 재앙 때 어린양의 피로 죽음이 넘어간 사건을 기념하는 절기.', ref:'출애굽기 12장' , en:'Passover', origin:'פֶּסַח', pron:'페사흐' },
  '무교절': { category:'용어', desc:'유월절에 이어 누룩 없는 빵을 먹으며 출애굽을 기념하는 절기.', ref:'출애굽기 12장' , en:'Unleavened Bread', origin:'מַצּוֹת', pron:'마초트' },
  '오순절': { category:'용어', desc:'유월절 후 50일째 절기. 신약에서 성령이 임한 날.', ref:'레위기 23장, 사도행전 2장' , en:'Pentecost', origin:'Πεντηκοστή', pron:'펜테코스테' },
  '초막절': { category:'용어', desc:'광야 생활을 기억하며 초막을 짓고 지키는 추수 감사 절기.', ref:'레위기 23장' , en:'Tabernacles', origin:'סֻכּוֹת', pron:'수코트' },
  '속죄일': { category:'용어', desc:'대제사장이 백성의 죄를 위해 속죄제를 드리는 가장 엄숙한 날.', ref:'레위기 16장' , en:'Day of Atonement', origin:'יוֹם כִּפּוּר', pron:'욤 키푸르' },
  '제사': { category:'용어', desc:'하나님께 짐승이나 곡식을 드려 죄 사함과 감사를 표현하는 예배 행위.', ref:'레위기' , en:'Sacrifice', origin:'זֶבַח', pron:'제바흐' },
  '번제': { category:'용어', desc:'제물을 완전히 불살라 드리는 헌신의 제사.', ref:'레위기 1장' , en:'Burnt Offering', origin:'עֹלָה', pron:'올라' },
  '속죄제': { category:'용어', desc:'죄를 용서받기 위해 드리는 제사.', ref:'레위기 4장' , en:'Sin Offering', origin:'חַטָּאת', pron:'하타트' },
  '성막': { category:'용어', desc:'광야 시대에 하나님이 임재하신 이동식 예배 처소.', ref:'출애굽기 25장 이하' , en:'Tabernacle', origin:'מִשְׁכָּן', pron:'미슈칸' },
  '법궤': { category:'용어', desc:'십계명 돌판을 담은 거룩한 궤. 언약궤라고도 한다.', ref:'출애굽기 25장' , en:'Ark of the Covenant', origin:'אֲרוֹן', pron:'아론' },
  '지성소': { category:'용어', desc:'성막·성전 가장 안쪽의 거룩한 공간. 대제사장만 일 년에 한 번 들어갔다.', ref:'출애굽기 26장, 히브리서 9장' , en:'Holy of Holies', origin:'קֹדֶשׁ הַקֳּדָשִׁים', pron:'코데시 하코다심' },
  '제사장': { category:'용어', desc:'하나님과 백성 사이에서 제사를 드리고 중재하는 직분. 아론과 그 자손이 맡았다.', ref:'출애굽기 28장' , en:'Priest', origin:'כֹּהֵן', pron:'코헨' },
  '대제사장': { category:'용어', desc:'제사장의 우두머리. 일 년에 한 번 지성소에 들어가 속죄했다.', ref:'레위기 16장, 히브리서' , en:'High Priest', origin:'כֹּהֵן גָּדוֹל', pron:'코헨 가돌' },
  '레위인': { category:'용어', desc:'성막·성전 봉사를 맡은 레위 지파 사람들.', ref:'민수기 3장' , en:'Levite', origin:'לֵוִי', pron:'레비' },
  '나실인': { category:'용어', desc:'특별히 구별되어 서원한 사람. 포도주를 금하고 머리를 깎지 않았다.', ref:'민수기 6장' , en:'Nazirite', origin:'נָזִיר', pron:'나지르' },
  '선지자': { category:'용어', desc:'하나님의 말씀을 받아 백성에게 전하는 사람. 예언자라고도 한다.', ref:'신명기 18장 등' , en:'Prophet', origin:'נָבִיא', pron:'나비' },
  '사사': { category:'용어', desc:'왕이 세워지기 전 이스라엘을 구원하고 다스린 지도자. 판관.', ref:'사사기' , en:'Judge', origin:'שֹׁפֵט', pron:'쇼페트' },
  '이스라엘': { category:'용어', desc:'야곱에게 주어진 이름이자 그 후손인 선민 공동체. 하나님과 겨루어 이겼다는 뜻.', ref:'창세기 32장' , en:'Israel', origin:'יִשְׂרָאֵל', pron:'이스라엘' },
  '선민': { category:'용어', desc:'하나님이 특별히 택하신 백성, 곧 이스라엘.', ref:'신명기 7장' , en:'Chosen People', origin:'עַם נִבְחָר', pron:'암 니브하르' },
  '회개': { category:'용어', desc:'죄에서 돌이켜 하나님께로 향하는 것.', ref:'마태복음 4:17 등' , en:'Repentance', origin:'μετάνοια', pron:'메타노이아' },
  '구원': { category:'용어', desc:'죄와 죽음에서 건짐받아 하나님과 화목하게 되는 것.', ref:'에베소서 2장 등' , en:'Salvation', origin:'σωτηρία', pron:'소테리아' },
  '복음': { category:'용어', desc:'예수 그리스도를 통한 구원의 기쁜 소식.', ref:'마가복음 1:1 등' , en:'Gospel', origin:'εὐαγγέλιον', pron:'유앙겔리온' },
  '은혜': { category:'용어', desc:'받을 자격 없는 자에게 베푸시는 하나님의 값없는 사랑과 호의.', ref:'에베소서 2:8' , en:'Grace', origin:'χάρις', pron:'카리스' },
  '믿음': { category:'용어', desc:'하나님과 그 약속을 신뢰하는 것. 구원의 통로.', ref:'히브리서 11장' , en:'Faith', origin:'πίστις', pron:'피스티스' },
  '의': { category:'용어', desc:'하나님 앞에서 올바른 상태. 믿음으로 의롭다 인정받는다.', ref:'로마서 3~4장' , en:'Righteousness', origin:'δικαιοσύνη', pron:'디카이오쉬네' },
  '거룩': { category:'용어', desc:'죄와 구별되어 하나님께 속한 상태.', ref:'레위기 11:44, 베드로전서 1장' , en:'Holiness', origin:'קֹדֶשׁ', pron:'코데시' },
  '죄': { category:'용어', desc:'하나님의 뜻을 어기고 그 영광에 이르지 못하는 것.', ref:'로마서 3:23' , en:'Sin', origin:'ἁμαρτία', pron:'하마르티아' },
  '속죄': { category:'용어', desc:'죄의 값을 대신 치러 하나님과 화해하게 하는 것.', ref:'레위기 16장, 로마서 3장' , en:'Atonement', origin:'כַּפָּרָה', pron:'카파라' },
  '부활': { category:'용어', desc:'죽은 자가 다시 살아나는 것. 예수의 부활이 그 첫 열매.', ref:'고린도전서 15장' , en:'Resurrection', origin:'ἀνάστασις', pron:'아나스타시스' },
  '영생': { category:'용어', desc:'예수를 믿는 자에게 주어지는 영원한 생명.', ref:'요한복음 3:16' , en:'Eternal Life', origin:'ζωὴ αἰώνιος', pron:'조에 아이오니오스' },
  '천국': { category:'용어', desc:'하나님이 다스리시는 나라. 하나님 나라라고도 한다.', ref:'마태복음 등' , en:'Kingdom of Heaven', origin:'βασιλεία τῶν οὐρανῶν', pron:'바실레이아' },
  '성령': { category:'용어', desc:'삼위일체 하나님의 한 위격. 믿는 자 안에 거하며 인도하신다.', ref:'요한복음 14장, 사도행전 2장' , en:'Holy Spirit', origin:'πνεῦμα', pron:'프뉴마' },
  '세례': { category:'용어', desc:'물로 죄 씻음과 새 생명을 상징하는 입교 예식.', ref:'마태복음 28:19' , en:'Baptism', origin:'βάπτισμα', pron:'밥티스마' },
  '성찬': { category:'용어', desc:'예수의 살과 피를 떡과 잔으로 기념하는 예식.', ref:'고린도전서 11장' , en:'Lord\'s Supper', origin:'κυριακὸν δεῖπνον', pron:'퀴리아콘 데이프논' },
  '제자': { category:'용어', desc:'예수를 따르며 배우고 그 가르침을 실천하는 사람.', ref:'마태복음 28:19' , en:'Disciple', origin:'μαθητής', pron:'마테테스' },
  '사도': { category:'용어', desc:'예수께 직접 보냄받아 복음을 전한 사람들. 열두 제자와 바울 등.', ref:'사도행전' , en:'Apostle', origin:'ἀπόστολος', pron:'아포스톨로스' },
  '이방인': { category:'용어', desc:'이스라엘 백성이 아닌 다른 민족 사람.', ref:'로마서 등' , en:'Gentile', origin:'ἔθνη', pron:'에트네' },
  '바리새인': { category:'용어', desc:'율법을 엄격히 지킨 유대 종교 지도층. 종종 예수와 충돌했다.', ref:'마태복음 23장' , en:'Pharisee', origin:'Φαρισαῖος', pron:'파리사이오스' },
  '사두개인': { category:'용어', desc:'부활을 믿지 않던 유대 제사장 계층의 지도층.', ref:'마태복음 22장' , en:'Sadducee', origin:'Σαδδουκαῖος', pron:'삿두카이오스' },
  '서기관': { category:'용어', desc:'율법을 베끼고 가르친 학자들. 율법학자.', ref:'마태복음 23장' , en:'Scribe', origin:'γραμματεύς', pron:'그람마테우스' },
  '산헤드린': { category:'용어', desc:'유대인의 최고 종교·자치 의회.', ref:'마태복음 26장, 사도행전' , en:'Sanhedrin', origin:'συνέδριον', pron:'쉬네드리온' },
  '회당': { category:'용어', desc:'유대인이 모여 말씀을 읽고 기도하던 지역 예배 처소.', ref:'누가복음 4장 등' , en:'Synagogue', origin:'συναγωγή', pron:'쉬나고게' },
  '비유': { category:'용어', desc:'일상의 이야기로 천국의 진리를 가르치신 예수의 교수법.', ref:'마태복음 13장' , en:'Parable', origin:'παραβολή', pron:'파라볼레' },
  '아멘': { category:'용어', desc:'진실로 그렇다, 그대로 이루어지기를 바란다는 뜻의 응답.', ref:'신명기 27장 등' , en:'Amen', origin:'אָמֵן', pron:'아멘' },
  '할렐루야': { category:'용어', desc:'여호와를 찬양하라는 뜻의 찬양 표현.', ref:'시편 등' , en:'Hallelujah', origin:'הַלְלוּיָהּ', pron:'할렐루야' },
  '호산나': { category:'용어', desc:'구원하소서라는 뜻의 외침. 예수의 예루살렘 입성 때 환호.', ref:'마태복음 21장' , en:'Hosanna', origin:'ὡσαννά', pron:'호산나' },
  '샬롬': { category:'용어', desc:'평화·평안·온전함을 뜻하는 히브리 인사말.', ref:'구약 전반' , en:'Peace', origin:'שָׁלוֹם', pron:'샬롬' },
  '기름부음': { category:'용어', desc:'왕·제사장·선지자를 세울 때 기름을 부어 거룩히 구별하던 의식.', ref:'사무엘상 16장' , en:'Anointing', origin:'מָשַׁח', pron:'마샤흐' },
  '성도': { category:'용어', desc:'거룩하게 구별된 하나님의 백성, 곧 믿는 자들.', ref:'로마서 1장 등' , en:'Saint', origin:'ἅγιος', pron:'하기오스' },
  '교회': { category:'용어', desc:'예수를 믿는 사람들의 모임이자 그리스도의 몸.', ref:'마태복음 16장, 에베소서' , en:'Church', origin:'ἐκκλησία', pron:'에클레시아' },
  '사랑': { category:'용어', desc:'하나님의 본질이며 가장 큰 계명. 조건 없이 베푸는 아가페 사랑을 가리킨다.', ref:'고린도전서 13장, 요한일서 4장', en:'Love', origin:'ἀγάπη', pron:'아가페' },
  '평화': { category:'용어', desc:'하나님과 사람, 사람과 사람 사이의 온전한 화평과 안녕. 히브리어 샬롬.', ref:'요한복음 14:27', en:'Peace', origin:'שָׁלוֹם', pron:'샬롬' },
  '아브라함의언약': { category:'용어', desc:'아브라함과 그 후손에게 땅·자손·복을 약속하신 언약.', ref:'창세기 15장, 17장' , en:'Abrahamic Covenant', origin:'בְּרִית', pron:'베리트' },
  '새언약': { category:'용어', desc:'예수의 피로 세워진 언약. 마음에 새겨진 율법.', ref:'예레미야 31장, 누가복음 22장' , en:'New Covenant', origin:'καινὴ διαθήκη', pron:'카이네 디아테케' },
  '화목제': { category:'용어', desc:'하나님과의 교제와 감사를 나누는 제사.', ref:'레위기 3장' , en:'Peace Offering', origin:'שְׁלָמִים', pron:'셸라밈' },
  '소제': { category:'용어', desc:'곡식 가루로 드리는 제사.', ref:'레위기 2장' , en:'Grain Offering', origin:'מִנְחָה', pron:'민하' },
  '속건제': { category:'용어', desc:'타인이나 성물에 해를 끼친 죄를 배상하며 드리는 제사.', ref:'레위기 5장' , en:'Guilt Offering', origin:'אָשָׁם', pron:'아샴' },
  '정결': { category:'용어', desc:'의식적·도덕적으로 깨끗하여 하나님께 나아갈 수 있는 상태.', ref:'레위기 11~15장' , en:'Clean', origin:'טָהוֹר', pron:'타호르' },
  '부정': { category:'용어', desc:'의식적으로 불결하여 성소에 나아갈 수 없는 상태.', ref:'레위기 11~15장' , en:'Unclean', origin:'טָמֵא', pron:'타메' },
  '우상': { category:'용어', desc:'하나님 외에 만들어 섬기는 형상이나 대상.', ref:'출애굽기 20장' , en:'Idol', origin:'אֱלִיל', pron:'엘릴' },
  '우상숭배': { category:'용어', desc:'하나님 아닌 것을 신으로 섬기는 죄.', ref:'출애굽기 20장' , en:'Idolatry', origin:'עֲבוֹדָה זָרָה', pron:'아보다 자라' },
  '바알': { category:'용어', desc:'가나안의 풍요 신. 이스라엘이 자주 빠진 우상.', ref:'사사기, 열왕기상' , en:'Baal', origin:'בַּעַל', pron:'바알' },
  '아세라': { category:'용어', desc:'가나안의 여신이자 그 목상.', ref:'사사기 6장' , en:'Asherah', origin:'אֲשֵׁרָה', pron:'아셰라' },
  '몰렉': { category:'용어', desc:'자녀를 불에 바치게 한 암몬의 잔혹한 신.', ref:'레위기 18장' , en:'Molech', origin:'מֹלֶךְ', pron:'몰레크' },
  '다곤': { category:'용어', desc:'블레셋의 신.', ref:'사사기 16장, 사무엘상 5장' , en:'Dagon', origin:'דָּגוֹן', pron:'다곤' },
  '스올': { category:'용어', desc:'죽은 자가 가는 곳을 가리키는 구약의 표현. 음부.', ref:'시편, 욥기' , en:'Sheol', origin:'שְׁאוֹל', pron:'셰올' },
  '음부': { category:'용어', desc:'죽은 자의 영역. 헬라어 하데스.', ref:'누가복음 16장' , en:'Hades', origin:'ᾅδης', pron:'하데스' },
  '게헨나': { category:'용어', desc:'최후 심판의 형벌 장소를 가리키는 말. 지옥.', ref:'마태복음 5장' , en:'Gehenna', origin:'γέεννα', pron:'게엔나' },
  '낙원': { category:'용어', desc:'의인이 죽은 후 누리는 복된 처소.', ref:'누가복음 23장' , en:'Paradise', origin:'παράδεισος', pron:'파라데이소스' },
  '종말': { category:'용어', desc:'역사의 마지막과 그리스도의 재림에 관한 일.', ref:'마태복음 24장' , en:'End Times', origin:'ἔσχατος', pron:'에스카토스' },
  '재림': { category:'용어', desc:'예수께서 영광 중에 다시 오시는 것.', ref:'사도행전 1장, 데살로니가전서 4장' , en:'Second Coming', origin:'παρουσία', pron:'파루시아' },
  '심판': { category:'용어', desc:'하나님이 각 사람의 행위를 판단하시는 것.', ref:'요한계시록 20장' , en:'Judgment', origin:'κρίσις', pron:'크리시스' },
  '천사': { category:'용어', desc:'하나님의 명령을 수행하는 영적 존재.', ref:'히브리서 1장' , en:'Angel', origin:'מַלְאָךְ', pron:'말아크' },
  '그룹': { category:'용어', desc:'하나님의 보좌와 성소를 지키는 천적 존재.', ref:'창세기 3장, 출애굽기 25장' , en:'Cherub', origin:'כְּרוּב', pron:'케루브' },
  '사탄': { category:'용어', desc:'하나님과 사람을 대적하는 악한 영의 우두머리. 마귀.', ref:'욥기, 마태복음 4장' , en:'Satan', origin:'שָׂטָן', pron:'사탄' },
  '마귀': { category:'용어', desc:'하나님을 대적하고 사람을 시험하는 악한 영.', ref:'마태복음 4장' , en:'Devil', origin:'διάβολος', pron:'디아볼로스' },
  '귀신': { category:'용어', desc:'사람을 괴롭히는 악한 영.', ref:'마가복음 5장' , en:'Demon', origin:'δαιμόνιον', pron:'다이모니온' },
  '예언': { category:'용어', desc:'하나님이 선지자를 통해 미리 알리시는 말씀.', ref:'베드로후서 1장' , en:'Prophecy', origin:'προφητεία', pron:'프로페테이아' },
  '환상': { category:'용어', desc:'하나님이 보여주시는 영적 광경.', ref:'사도행전 10장' , en:'Vision', origin:'חָזוֹן', pron:'하존' },
  '이적': { category:'용어', desc:'하나님의 능력으로 일어나는 표적과 기사.', ref:'요한복음 2장' , en:'Sign', origin:'σημεῖον', pron:'세메이온' },
  '기적': { category:'용어', desc:'자연을 초월한 하나님의 놀라운 일.', ref:'사복음서' , en:'Miracle', origin:'δύναμις', pron:'뒤나미스' },
  '축복': { category:'용어', desc:'하나님이 베푸시는 은총과 잘됨을 비는 것.', ref:'민수기 6장' , en:'Blessing', origin:'בְּרָכָה', pron:'베라카' },
  '저주': { category:'용어', desc:'축복의 반대로, 죄에 따르는 재앙의 선언.', ref:'신명기 27~28장' , en:'Curse', origin:'קְלָלָה', pron:'켈랄라' },
  '기도': { category:'용어', desc:'하나님께 아뢰고 교제하는 것.', ref:'마태복음 6장' , en:'Prayer', origin:'προσευχή', pron:'프로슈케' },
  '금식': { category:'용어', desc:'음식을 끊고 하나님께 집중하며 간구하는 일.', ref:'마태복음 6장' , en:'Fasting', origin:'νηστεία', pron:'네스테이아' },
  '찬양': { category:'용어', desc:'하나님의 위대하심과 은혜를 노래하고 높이는 것.', ref:'시편' , en:'Praise', origin:'תְּהִלָּה', pron:'테힐라' },
  '경배': { category:'용어', desc:'하나님께 엎드려 존귀와 영광을 돌리는 것.', ref:'요한복음 4장' , en:'Worship', origin:'προσκυνέω', pron:'프로스퀴네오' },
  '전도': { category:'용어', desc:'복음을 전하여 사람을 그리스도께 인도하는 일.', ref:'마태복음 28장' , en:'Evangelism', origin:'εὐαγγελίζω', pron:'유앙겔리조' },
  '선교': { category:'용어', desc:'복음을 모든 민족에게 전하는 사명.', ref:'사도행전 1장' , en:'Mission', origin:'ἀποστολή', pron:'아포스톨레' },
  '부흥': { category:'용어', desc:'식어진 신앙이 성령으로 새롭게 살아나는 것.', ref:'사도행전 2장' , en:'Revival', origin:'ἀναζάω', pron:'아나자오' },
  '거듭남': { category:'용어', desc:'성령으로 새 사람으로 다시 태어나는 것. 중생.', ref:'요한복음 3장' , en:'Born Again', origin:'ἀναγεννάω', pron:'아나겐나오' },
  '칭의': { category:'용어', desc:'믿음으로 의롭다 인정받는 것.', ref:'로마서 5장' , en:'Justification', origin:'δικαίωσις', pron:'디카이오시스' },
  '성화': { category:'용어', desc:'구원받은 자가 점점 거룩해져 가는 과정.', ref:'데살로니가전서 4장' , en:'Sanctification', origin:'ἁγιασμός', pron:'하기아스모스' },
  '영화': { category:'용어', desc:'구원의 완성으로 영광스러운 몸을 입게 되는 것.', ref:'로마서 8장' , en:'Glorification', origin:'δοξάζω', pron:'독사조' },
  '예정': { category:'용어', desc:'하나님이 미리 택하여 정하신 구원의 계획.', ref:'에베소서 1장' , en:'Predestination', origin:'προορίζω', pron:'프로오리조' },
  '화목': { category:'용어', desc:'죄로 단절된 하나님과 사람이 다시 하나 되는 것.', ref:'고린도후서 5장' , en:'Reconciliation', origin:'καταλλαγή', pron:'카탈라게' },
  '대속': { category:'용어', desc:'예수께서 사람의 죄값을 대신 치르신 것.', ref:'마가복음 10:45' , en:'Redemption', origin:'ἀπολύτρωσις', pron:'아폴뤼트로시스' },
  '십자가': { category:'용어', desc:'예수께서 죽으신 형틀이자 그 희생과 구원의 상징.', ref:'고린도전서 1장' , en:'Cross', origin:'σταυρός', pron:'스타우로스' },
  '보혈': { category:'용어', desc:'죄를 씻는 예수의 보배로운 피.', ref:'베드로전서 1장' , en:'Precious Blood', origin:'αἷμα', pron:'하이마' },
  '어린양': { category:'용어', desc:'희생제물 되신 예수를 가리키는 상징.', ref:'요한복음 1:29, 요한계시록 5장' , en:'Lamb', origin:'ἀμνός', pron:'암노스' },
  '반석': { category:'용어', desc:'견고한 구원의 기초이신 하나님·그리스도를 가리키는 상징.', ref:'시편 18편, 고린도전서 10장' , en:'Rock', origin:'צוּר', pron:'추르' },
  '목자': { category:'용어', desc:'양 떼를 돌보듯 백성을 인도하시는 하나님·예수의 상징.', ref:'시편 23편, 요한복음 10장' , en:'Shepherd', origin:'ποιμήν', pron:'포이멘' },
  '포도나무': { category:'용어', desc:'예수와 그를 믿는 자의 연합을 나타내는 상징.', ref:'요한복음 15장' , en:'Vine', origin:'ἄμπελος', pron:'암펠로스' },
  '빛': { category:'용어', desc:'진리와 생명, 하나님의 임재를 나타내는 상징.', ref:'요한복음 8장' , en:'Light', origin:'φῶς', pron:'포스' },
  '소금': { category:'용어', desc:'세상을 정결케 하고 부패를 막는 성도의 역할 상징.', ref:'마태복음 5장' , en:'Salt', origin:'ἅλας', pron:'할라스' },
  '말씀': { category:'용어', desc:'하나님의 계시이자 성육신하신 그리스도(로고스).', ref:'요한복음 1장' , en:'Word', origin:'λόγος', pron:'로고스' },
  '로고스': { category:'용어', desc:'말씀이라는 뜻의 헬라어. 요한복음에서 그리스도를 가리킨다.', ref:'요한복음 1장' , en:'Word / Logos', origin:'λόγος', pron:'로고스' },
  '삼위일체': { category:'용어', desc:'성부·성자·성령이 한 하나님이심을 나타내는 교리.', ref:'마태복음 28:19' , en:'Trinity', origin:'τριάς', pron:'트리아스' },
  '아비멜렉': { category:'인물', desc:'그랄 왕의 칭호. 아브라함·이삭과 우물 언약을 맺었다. 또 기드온의 아들로 왕이 되려 한 자도 동명이다.', ref:'창세기 20~26장, 사사기 9장', en:'Abimelech', origin:'אֲבִימֶלֶךְ', pron:'아비멜레크' },
  '멜기세덱': { category:'인물', desc:'살렘 왕이자 지극히 높으신 하나님의 제사장. 아브라함을 축복했고 그리스도의 예표로 본다.', ref:'창세기 14장, 히브리서 7장', en:'Melchizedek', origin:'מַלְכִּי־צֶדֶק', pron:'말키체데크' },
  '엘리에셀': { category:'인물', desc:'아브라함의 충성된 종으로 이삭의 아내를 구하러 갔다.', ref:'창세기 24장', en:'Eliezer', origin:'אֱלִיעֶזֶר', pron:'엘리에제르' },
  '디나': { category:'인물', desc:'야곱과 레아의 딸.', ref:'창세기 34장', en:'Dinah', origin:'דִּינָה', pron:'디나' },
  '다말': { category:'인물', desc:'유다의 며느리로 베레스를 낳아 다윗의 계보를 이었다.', ref:'창세기 38장', en:'Tamar', origin:'תָּמָר', pron:'타마르' },
  '에브라임': { category:'인물', desc:'요셉의 둘째 아들. 이스라엘 한 지파의 조상.', ref:'창세기 41장, 48장', en:'Ephraim', origin:'אֶפְרַיִם', pron:'에프라임' },
  '므낫세': { category:'인물', desc:'요셉의 맏아들. 이스라엘 한 지파의 조상.', ref:'창세기 41장, 48장', en:'Manasseh', origin:'מְנַשֶּׁה', pron:'메낫셰' },
  '레위': { category:'인물', desc:'야곱의 셋째 아들. 제사장 지파인 레위 지파의 조상.', ref:'창세기 29장, 34장', en:'Levi', origin:'לֵוִי', pron:'레비' },
  '시므온(야곱아들)': { category:'인물', desc:'야곱의 둘째 아들. 시므온 지파의 조상.', ref:'창세기 29장, 34장', en:'Simeon', origin:'שִׁמְעוֹן', pron:'쉼온' },
  '르우벤': { category:'인물', desc:'야곱의 맏아들. 르우벤 지파의 조상.', ref:'창세기 29장', en:'Reuben', origin:'רְאוּבֵן', pron:'레우벤' },
  '이드로': { category:'인물', desc:'모세의 장인이자 미디안 제사장. 모세에게 재판 제도를 조언했다.', ref:'출애굽기 18장', en:'Jethro', origin:'יִתְרוֹ', pron:'이트로' },
  '십보라': { category:'인물', desc:'모세의 아내이며 이드로의 딸.', ref:'출애굽기 2장, 18장', en:'Zipporah', origin:'צִפֹּרָה', pron:'치포라' },
  '고라': { category:'인물', desc:'모세와 아론의 권위에 반역하다 심판받은 레위인.', ref:'민수기 16장', en:'Korah', origin:'קֹרַח', pron:'코라흐' },
  '아말렉': { category:'인물', desc:'이스라엘을 광야에서 공격한 족속이자 그 조상.', ref:'출애굽기 17장', en:'Amalek', origin:'עֲמָלֵק', pron:'아말레크' },
  '옥': { category:'인물', desc:'이스라엘이 무찌른 바산의 거인 왕.', ref:'민수기 21장, 신명기 3장', en:'Og', origin:'עוֹג', pron:'오그' },
  '시혼': { category:'인물', desc:'이스라엘이 무찌른 아모리 왕.', ref:'민수기 21장', en:'Sihon', origin:'סִיחוֹן', pron:'시혼' },
  '아도니베섹': { category:'인물', desc:'유다 지파에게 패한 가나안 왕.', ref:'사사기 1장', en:'Adoni-bezek', origin:'אֲדֹנִי־בֶזֶק', pron:'아도니베제크' },
  '에글론': { category:'인물', desc:'에훗에게 죽임당한 모압 왕.', ref:'사사기 3장', en:'Eglon', origin:'עֶגְלוֹן', pron:'에글론' },
  '야엘': { category:'인물', desc:'장막 말뚝으로 적장 시스라를 처치한 여인.', ref:'사사기 4장', en:'Jael', origin:'יָעֵל', pron:'야엘' },
  '시스라': { category:'인물', desc:'드보라·바락에게 패한 가나안 군대장관.', ref:'사사기 4장', en:'Sisera', origin:'סִיסְרָא', pron:'시스라' },
  '아비멜렉(기드온아들)': { category:'인물', desc:'기드온의 아들로 형제들을 죽이고 왕이 되려다 멸망한 자.', ref:'사사기 9장', en:'Abimelech', origin:'אֲבִימֶלֶךְ', pron:'아비멜레크' },
  '입산': { category:'인물', desc:'이스라엘의 사사 중 하나.', ref:'사사기 12장', en:'Ibzan', origin:'אִבְצָן', pron:'이브찬' },
  '들릴라': { category:'인물', desc:'삼손의 머리카락 비밀을 알아내 블레셋에 넘긴 여인.', ref:'사사기 16장', en:'Delilah', origin:'דְּלִילָה', pron:'델릴라' },
  '엘가나': { category:'인물', desc:'사무엘의 아버지이자 한나의 남편.', ref:'사무엘상 1장', en:'Elkanah', origin:'אֶלְקָנָה', pron:'엘카나' },
  '아비나답': { category:'인물', desc:'법궤를 보관했던 사람. 또 다윗의 형 이름도 동일.', ref:'사무엘상 7장, 16장', en:'Abinadab', origin:'אֲבִינָדָב', pron:'아비나다브' },
  '아기스': { category:'인물', desc:'다윗이 피신했던 가드의 블레셋 왕.', ref:'사무엘상 21장, 27장', en:'Achish', origin:'אָכִישׁ', pron:'아키시' },
  '아비가일(다윗아내)': { category:'인물', desc:'나발의 아내였다가 다윗의 아내가 된 지혜로운 여인.', ref:'사무엘상 25장', en:'Abigail', origin:'אֲבִיגַיִל', pron:'아비가일' },
  '나발': { category:'인물', desc:'다윗을 모욕한 부유하고 어리석은 자. 아비가일의 남편.', ref:'사무엘상 25장', en:'Nabal', origin:'נָבָל', pron:'나발' },
  '아브넬': { category:'인물', desc:'사울의 군대장관.', ref:'사무엘하 2~3장', en:'Abner', origin:'אַבְנֵר', pron:'아브네르' },
  '이스보셋': { category:'인물', desc:'사울의 아들로 잠시 왕이 되었다.', ref:'사무엘하 2~4장', en:'Ishbosheth', origin:'אִישׁ־בֹּשֶׁת', pron:'이시보셰트' },
  '우리아': { category:'인물', desc:'밧세바의 남편으로 다윗에 의해 전사한 충신.', ref:'사무엘하 11장', en:'Uriah', origin:'אוּרִיָּה', pron:'우리야' },
  '다말(다윗딸)': { category:'인물', desc:'다윗의 딸로 암논에게 욕을 당했다.', ref:'사무엘하 13장', en:'Tamar', origin:'תָּמָר', pron:'타마르' },
  '암논': { category:'인물', desc:'다윗의 맏아들로 누이 다말을 범해 압살롬에게 죽었다.', ref:'사무엘하 13장', en:'Amnon', origin:'אַמְנוֹן', pron:'암논' },
  '아히도벨': { category:'인물', desc:'압살롬의 반역을 도운 다윗의 모사.', ref:'사무엘하 15~17장', en:'Ahithophel', origin:'אֲחִיתֹפֶל', pron:'아히토펠' },
  '후새': { category:'인물', desc:'압살롬의 모략을 무너뜨린 다윗의 충신.', ref:'사무엘하 15~17장', en:'Hushai', origin:'חוּשַׁי', pron:'후샤이' },
  '시므이': { category:'인물', desc:'다윗을 저주한 베냐민 사람.', ref:'사무엘하 16장', en:'Shimei', origin:'שִׁמְעִי', pron:'쉼이' },
  '스바': { category:'인물', desc:'다윗에게 반역한 베냐민 사람.', ref:'사무엘하 20장', en:'Sheba', origin:'שֶׁבַע', pron:'셰바' },
  '요나답': { category:'인물', desc:'암논에게 간계를 일러준 자.', ref:'사무엘하 13장', en:'Jonadab', origin:'יוֹנָדָב', pron:'요나다브' },
  '아도니야(왕자)': { category:'인물', desc:'솔로몬에 앞서 왕이 되려 한 다윗의 아들.', ref:'열왕기상 1장', en:'Adonijah', origin:'אֲדֹנִיָּהוּ', pron:'아도니야후' },
  '스바여왕': { category:'인물', desc:'솔로몬의 지혜를 시험하러 온 여왕.', ref:'열왕기상 10장', en:'Queen of Sheba', origin:'מַלְכַּת־שְׁבָא', pron:'말카트 셰바' },
  '아사': { category:'인물', desc:'유다의 경건한 개혁 군주.', ref:'열왕기상 15장', en:'Asa', origin:'אָסָא', pron:'아사' },
  '여호사밧': { category:'인물', desc:'유다의 경건한 왕으로 종교 개혁을 했다.', ref:'열왕기상 22장', en:'Jehoshaphat', origin:'יְהוֹשָׁפָט', pron:'예호샤파트' },
  '아하시야': { category:'인물', desc:'북이스라엘과 유다에 각각 있던 왕 이름.', ref:'열왕기상 22장, 열왕기하 8장', en:'Ahaziah', origin:'אֲחַזְיָהוּ', pron:'아하즈야후' },
  '요람': { category:'인물', desc:'이스라엘·유다의 왕 이름. 여호람이라고도 한다.', ref:'열왕기하 1장, 8장', en:'Joram', origin:'יוֹרָם', pron:'요람' },
  '예후': { category:'인물', desc:'이세벨과 아합 가문을 멸한 이스라엘 왕.', ref:'열왕기하 9~10장', en:'Jehu', origin:'יֵהוּא', pron:'예후' },
  '아달랴': { category:'인물', desc:'유다 왕위를 찬탈한 악한 왕비.', ref:'열왕기하 11장', en:'Athaliah', origin:'עֲתַלְיָהוּ', pron:'아탈야후' },
  '요아스': { category:'인물', desc:'어린 나이에 구출되어 왕이 된 유다 왕.', ref:'열왕기하 11~12장', en:'Joash', origin:'יוֹאָשׁ', pron:'요아시' },
  '웃시야': { category:'인물', desc:'교만으로 나병에 걸린 유다 왕. 아사랴라고도 한다.', ref:'열왕기하 15장, 역대하 26장', en:'Uzziah', origin:'עֻזִּיָּהוּ', pron:'우찌야후' },
  '아하스': { category:'인물', desc:'우상을 섬긴 유다의 악한 왕.', ref:'열왕기하 16장', en:'Ahaz', origin:'אָחָז', pron:'아하즈' },
  '므낫세(유다왕)': { category:'인물', desc:'유다의 가장 악했던 왕이나 말년에 회개했다.', ref:'열왕기하 21장, 역대하 33장', en:'Manasseh', origin:'מְנַשֶּׁה', pron:'메낫셰' },
  '시드기야': { category:'인물', desc:'유다의 마지막 왕. 바벨론에 끌려갔다.', ref:'열왕기하 24~25장', en:'Zedekiah', origin:'צִדְקִיָּהוּ', pron:'치드키야후' },
  '여호야긴': { category:'인물', desc:'바벨론에 포로로 끌려간 유다 왕.', ref:'열왕기하 24장', en:'Jehoiachin', origin:'יְהוֹיָכִין', pron:'예호야킨' },
  '스룹바벨': { category:'인물', desc:'포로 귀환 후 성전 재건을 이끈 유다 총독.', ref:'에스라 3장, 학개', en:'Zerubbabel', origin:'זְרֻבָּבֶל', pron:'제루바벨' },
  '여호수아(대제사장)': { category:'인물', desc:'포로 귀환 후 성전 재건기의 대제사장.', ref:'학개 1장, 스가랴 3장', en:'Joshua', origin:'יְהוֹשֻׁעַ', pron:'예호슈아' },
  '하만': { category:'인물', desc:'유대인을 멸하려다 자기가 매달린 페르시아의 총리.', ref:'에스더 3~7장', en:'Haman', origin:'הָמָן', pron:'하만' },
  '아하수에로': { category:'인물', desc:'에스더가 왕비가 된 페르시아의 왕.', ref:'에스더 1장', en:'Ahasuerus', origin:'אֲחַשְׁוֵרוֹשׁ', pron:'아하슈베로시' },
  '와스디': { category:'인물', desc:'아하수에로의 명을 거역해 폐위된 왕비.', ref:'에스더 1장', en:'Vashti', origin:'וַשְׁתִּי', pron:'바슈티' },
  '고레스': { category:'인물', desc:'유대인의 귀환을 명령한 페르시아의 왕. 키루스.', ref:'에스라 1장, 이사야 45장', en:'Cyrus', origin:'כּוֹרֶשׁ', pron:'코레시' },
  '다리오': { category:'인물', desc:'성전 재건을 도운 페르시아 왕. 다니엘서에도 등장.', ref:'에스라 6장, 다니엘 6장', en:'Darius', origin:'דָּרְיָוֶשׁ', pron:'다르야베시' },
  '사드락': { category:'인물', desc:'풀무불에서 구원받은 다니엘의 세 친구 중 하나.', ref:'다니엘 3장', en:'Shadrach', origin:'שַׁדְרַךְ', pron:'샤드라크' },
  '메삭': { category:'인물', desc:'풀무불에서 구원받은 다니엘의 세 친구 중 하나.', ref:'다니엘 3장', en:'Meshach', origin:'מֵישַׁךְ', pron:'메샤크' },
  '아벳느고': { category:'인물', desc:'풀무불에서 구원받은 다니엘의 세 친구 중 하나.', ref:'다니엘 3장', en:'Abednego', origin:'עֲבֵד נְגוֹ', pron:'아베드 네고' },
  '벨사살': { category:'인물', desc:'벽에 나타난 글자로 멸망이 선고된 바벨론의 마지막 왕.', ref:'다니엘 5장', en:'Belshazzar', origin:'בֵּלְשַׁאצַּר', pron:'벨샤차르' },
  '고멜': { category:'인물', desc:'호세아 선지자의 음란한 아내. 이스라엘의 영적 간음을 상징.', ref:'호세아 1장', en:'Gomer', origin:'גֹּמֶר', pron:'고메르' },
  '사가랴': { category:'인물', desc:'세례 요한의 아버지인 제사장. 스가랴의 신약 표기.', ref:'누가복음 1장', en:'Zechariah', origin:'Ζαχαρίας', pron:'자카리아스' },
  '시몬(베드로형제외)': { category:'인물', desc:'구레네 사람으로 예수의 십자가를 대신 진 자.', ref:'마가복음 15장', en:'Simon', origin:'Σίμων', pron:'시몬' },
  '바라바': { category:'인물', desc:'예수 대신 풀려난 죄수.', ref:'마태복음 27장', en:'Barabbas', origin:'Βαραββᾶς', pron:'바라바스' },
  '아리마대요셉': { category:'인물', desc:'예수의 시신을 거두어 장사 지낸 의회 의원.', ref:'요한복음 19장', en:'Joseph of Arimathea', origin:'Ἰωσήφ', pron:'이오세프' },
  '헤로디아': { category:'인물', desc:'세례 요한을 죽게 한 헤롯의 아내.', ref:'마가복음 6장', en:'Herodias', origin:'Ἡρῳδιάς', pron:'헤로디아스' },
  '야이로': { category:'인물', desc:'예수께서 딸을 살려주신 회당장.', ref:'마가복음 5장', en:'Jairus', origin:'Ἰάειρος', pron:'이아이로스' },
  '레위(세리)': { category:'인물', desc:'세리였다가 예수를 따른 제자. 마태의 다른 이름.', ref:'마가복음 2장', en:'Levi', origin:'Λευί', pron:'레비' },
  '나다나엘': { category:'인물', desc:'예수께서 참 이스라엘 사람이라 부른 제자. 바돌로매로 본다.', ref:'요한복음 1장', en:'Nathanael', origin:'Ναθαναήλ', pron:'나타나엘' },
  '바돌로매': { category:'인물', desc:'예수의 열두 제자 중 하나. 나다나엘과 동일시된다.', ref:'마태복음 10장', en:'Bartholomew', origin:'Βαρθολομαῖος', pron:'바르톨로마이오스' },
  '다대오': { category:'인물', desc:'예수의 열두 제자 중 하나.', ref:'마태복음 10장', en:'Thaddaeus', origin:'Θαδδαῖος', pron:'탓다이오스' },
  '마티아': { category:'인물', desc:'가룟 유다를 대신해 뽑힌 사도.', ref:'사도행전 1장', en:'Matthias', origin:'Μαθθίας', pron:'맛티아스' },
  '빌립(집사)': { category:'인물', desc:'일곱 집사 중 하나로 사마리아와 에디오피아 내시에게 복음을 전했다.', ref:'사도행전 6장, 8장', en:'Philip', origin:'Φίλιππος', pron:'필립포스' },
  '시몬(마술사)': { category:'인물', desc:'성령을 돈으로 사려 한 사마리아의 마술사.', ref:'사도행전 8장', en:'Simon Magus', origin:'Σίμων', pron:'시몬' },
  '다비다': { category:'인물', desc:'베드로가 살린 욥바의 여제자. 도르가라고도 한다.', ref:'사도행전 9장', en:'Tabitha', origin:'Ταβιθά', pron:'타비타' },
  '애니아': { category:'인물', desc:'베드로를 통해 중풍에서 나은 사람.', ref:'사도행전 9장', en:'Aeneas', origin:'Αἰνέας', pron:'아이네아스' },
  '헤롯아그립바': { category:'인물', desc:'야고보를 죽이고 베드로를 가둔 왕.', ref:'사도행전 12장', en:'Herod Agrippa', origin:'Ἡρῴδης', pron:'헤로데스' },
  '엘루마': { category:'인물', desc:'바울의 복음을 방해하다 눈먼 마술사. 바예수.', ref:'사도행전 13장', en:'Elymas', origin:'Ἐλύμας', pron:'엘뤼마스' },
  '서기오바울': { category:'인물', desc:'바울을 통해 믿게 된 구브로의 총독.', ref:'사도행전 13장', en:'Sergius Paulus', origin:'Σέργιος Παῦλος', pron:'세르기오스' },
  '가이오': { category:'인물', desc:'바울의 동행자이자 접대한 신자.', ref:'사도행전 19장, 로마서 16장', en:'Gaius', origin:'Γάϊος', pron:'가이오스' },
  '드로비모': { category:'인물', desc:'바울과 동행한 에베소 출신 신자.', ref:'사도행전 21장', en:'Trophimus', origin:'Τρόφιμος', pron:'트로피모스' },
  '벨릭스': { category:'인물', desc:'바울을 재판한 로마 총독.', ref:'사도행전 24장', en:'Felix', origin:'Φῆλιξ', pron:'펠릭스' },
  '베스도': { category:'인물', desc:'벨릭스를 이은 로마 총독.', ref:'사도행전 25장', en:'Festus', origin:'Φῆστος', pron:'페스토스' },
  '아그립바': { category:'인물', desc:'바울의 변론을 들은 왕.', ref:'사도행전 26장', en:'Agrippa', origin:'Ἀγρίππας', pron:'아그립파스' },
  '유두고': { category:'인물', desc:'바울의 설교 중 졸다 떨어졌으나 살아난 청년.', ref:'사도행전 20장', en:'Eutychus', origin:'Εὔτυχος', pron:'유튀코스' },
  '아킵보': { category:'인물', desc:'골로새 교회의 일꾼.', ref:'골로새 4장, 빌레몬서', en:'Archippus', origin:'Ἄρχιππος', pron:'아르킵포스' },
  '에바브로디도': { category:'인물', desc:'빌립보 교회가 바울에게 보낸 사자.', ref:'빌립보서 2장', en:'Epaphroditus', origin:'Ἐπαφρόδιτος', pron:'에파프로디토스' },
  '유오디아': { category:'인물', desc:'빌립보 교회의 두 여성 일꾼 중 하나.', ref:'빌립보서 4장', en:'Euodia', origin:'Εὐοδία', pron:'유오디아' },
  '순두게': { category:'인물', desc:'빌립보 교회의 두 여성 일꾼 중 하나.', ref:'빌립보서 4장', en:'Syntyche', origin:'Συντύχη', pron:'쉰튀케' },
  '후메내오': { category:'인물', desc:'믿음에서 떠나 바울이 경계한 자.', ref:'디모데전서 1장', en:'Hymenaeus', origin:'Ὑμέναιος', pron:'휘메나이오스' },
  '알렉산더': { category:'인물', desc:'바울을 대적한 구리 세공업자.', ref:'디모데후서 4장', en:'Alexander', origin:'Ἀλέξανδρος', pron:'알렉산드로스' },
  '로이스': { category:'인물', desc:'디모데의 외할머니로 믿음의 사람.', ref:'디모데후서 1장', en:'Lois', origin:'Λωΐς', pron:'로이스' },
  '유니게': { category:'인물', desc:'디모데의 어머니로 믿음의 사람.', ref:'디모데후서 1장', en:'Eunice', origin:'Εὐνίκη', pron:'유니케' },
  '하란': { category:'지명', desc:'아브라함이 가나안으로 가기 전 머문 곳. 나홀의 성.', ref:'창세기 11~12장', en:'Haran', origin:'חָרָן', pron:'하란' },
  '그랄': { category:'지명', desc:'아브라함과 이삭이 머문 블레셋 지역의 성읍.', ref:'창세기 20장, 26장', en:'Gerar', origin:'גְּרָר', pron:'게라르' },
  '브니엘': { category:'지명', desc:'야곱이 하나님과 씨름하고 이름을 받은 곳. 하나님의 얼굴이라는 뜻.', ref:'창세기 32장', en:'Peniel', origin:'פְּנִיאֵל', pron:'페니엘' },
  '세겜': { category:'지명', desc:'아브라함이 처음 제단을 쌓고 야곱이 머문 중부의 성읍.', ref:'창세기 12장, 33장', en:'Shechem', origin:'שְׁכֶם', pron:'셰켐' },
  '막벨라': { category:'지명', desc:'아브라함이 사라를 장사한 헤브론의 굴.', ref:'창세기 23장', en:'Machpelah', origin:'מַכְפֵּלָה', pron:'마크펠라' },
  '고센': { category:'지명', desc:'야곱 일가가 애굽에서 정착해 산 비옥한 땅.', ref:'창세기 47장', en:'Goshen', origin:'גֹּשֶׁן', pron:'고셴' },
  '마라': { category:'지명', desc:'출애굽 후 쓴 물이 단물로 변한 곳.', ref:'출애굽기 15장', en:'Marah', origin:'מָרָה', pron:'마라' },
  '엘림': { category:'지명', desc:'샘과 종려나무가 있던 광야의 오아시스.', ref:'출애굽기 15장', en:'Elim', origin:'אֵילִם', pron:'엘림' },
  '르비딤': { category:'지명', desc:'반석에서 물이 나오고 아말렉과 싸운 곳.', ref:'출애굽기 17장', en:'Rephidim', origin:'רְפִידִים', pron:'레피딤' },
  '가데스바네아': { category:'지명', desc:'이스라엘이 정탐꾼을 보낸 광야의 진영지.', ref:'민수기 13장', en:'Kadesh-barnea', origin:'קָדֵשׁ בַּרְנֵעַ', pron:'카데시 바르네아' },
  '느보산': { category:'지명', desc:'모세가 가나안 땅을 바라보고 죽은 산.', ref:'신명기 34장', en:'Mount Nebo', origin:'הַר נְבוֹ', pron:'하르 네보' },
  '아이': { category:'지명', desc:'여리고 다음으로 정복한 성. 아간의 죄로 처음엔 패했다.', ref:'여호수아 7~8장', en:'Ai', origin:'עַי', pron:'아이' },
  '기브온': { category:'지명', desc:'속임수로 이스라엘과 화친을 맺은 성읍.', ref:'여호수아 9장', en:'Gibeon', origin:'גִּבְעוֹן', pron:'기브온' },
  '길갈': { category:'지명', desc:'요단을 건넌 이스라엘이 처음 진을 친 곳.', ref:'여호수아 4~5장', en:'Gilgal', origin:'גִּלְגָּל', pron:'길갈' },
  '미스바': { category:'지명', desc:'이스라엘이 모여 회개하고 기도한 집회 장소.', ref:'사사기 20장, 사무엘상 7장', en:'Mizpah', origin:'מִצְפָּה', pron:'미츠파' },
  '라마': { category:'지명', desc:'사무엘의 고향이자 활동 중심지.', ref:'사무엘상 7장', en:'Ramah', origin:'רָמָה', pron:'라마' },
  '놉': { category:'지명', desc:'다윗이 도망 중 들른 제사장들의 성읍.', ref:'사무엘상 21장', en:'Nob', origin:'נֹב', pron:'노브' },
  '그일라': { category:'지명', desc:'다윗이 블레셋에서 구원한 성읍.', ref:'사무엘상 23장', en:'Keilah', origin:'קְעִילָה', pron:'케일라' },
  '시글락': { category:'지명', desc:'블레셋 왕이 다윗에게 준 성읍.', ref:'사무엘상 27장', en:'Ziklag', origin:'צִקְלַג', pron:'치클라그' },
  '길보아': { category:'지명', desc:'사울과 요나단이 전사한 산.', ref:'사무엘상 31장', en:'Mount Gilboa', origin:'גִּלְבֹּעַ', pron:'길보아' },
  '마하나임': { category:'지명', desc:'다윗이 압살롬을 피해 머문 요단 동편의 성.', ref:'사무엘하 17장', en:'Mahanaim', origin:'מַחֲנַיִם', pron:'마하나임' },
  '기브아': { category:'지명', desc:'사울의 고향.', ref:'사무엘상 10장', en:'Gibeah', origin:'גִּבְעָה', pron:'기브아' },
  '아둘람': { category:'지명', desc:'다윗이 사울을 피해 숨은 굴.', ref:'사무엘상 22장', en:'Adullam', origin:'עֲדֻלָּם', pron:'아둘람' },
  '엔게디': { category:'지명', desc:'다윗이 사울을 피한 사해 서편의 오아시스.', ref:'사무엘상 24장', en:'En-gedi', origin:'עֵין גֶּדִי', pron:'에인 게디' },
  '그릿시냇가': { category:'지명', desc:'엘리야가 까마귀에게 먹이를 받은 시냇가.', ref:'열왕기상 17장', en:'Brook Cherith', origin:'נַחַל כְּרִית', pron:'케리트' },
  '사르밧': { category:'지명', desc:'엘리야가 과부의 집에 머문 시돈 지역의 마을.', ref:'열왕기상 17장', en:'Zarephath', origin:'צָרְפַת', pron:'차르파트' },
  '수넴': { category:'지명', desc:'엘리사가 한 여인의 죽은 아들을 살린 마을.', ref:'열왕기하 4장', en:'Shunem', origin:'שׁוּנֵם', pron:'슈넴' },
  '도단': { category:'지명', desc:'요셉이 형들에게 팔리고, 엘리사가 천군을 본 곳.', ref:'창세기 37장, 열왕기하 6장', en:'Dothan', origin:'דֹּתָן', pron:'도탄' },
  '벧세메스': { category:'지명', desc:'법궤가 블레셋에서 돌아온 성읍.', ref:'사무엘상 6장', en:'Beth-shemesh', origin:'בֵּית שֶׁמֶשׁ', pron:'베이트 셰메시' },
  '아벡': { category:'지명', desc:'이스라엘이 블레셋에 패해 법궤를 빼앗긴 곳.', ref:'사무엘상 4장', en:'Aphek', origin:'אֲפֵק', pron:'아페크' },
  '그리심산': { category:'지명', desc:'축복을 선포한 산. 사마리아인의 예배처.', ref:'신명기 11장, 요한복음 4장', en:'Mount Gerizim', origin:'הַר גְּרִזִים', pron:'하르 게리짐' },
  '에발산': { category:'지명', desc:'저주를 선포한 산.', ref:'신명기 11장, 27장', en:'Mount Ebal', origin:'הַר עֵיבָל', pron:'하르 에발' },
  '다볼산': { category:'지명', desc:'드보라와 바락이 군대를 모은 산. 변화산으로도 전승된다.', ref:'사사기 4장', en:'Mount Tabor', origin:'הַר תָּבוֹר', pron:'하르 타보르' },
  '헐몬산': { category:'지명', desc:'이스라엘 북쪽 경계의 높은 산.', ref:'신명기 3장, 시편 133편', en:'Mount Hermon', origin:'חֶרְמוֹן', pron:'헤르몬' },
  '기드론골짜기': { category:'지명', desc:'예루살렘 동편의 골짜기. 예수께서 건너 겟세마네로 가셨다.', ref:'사무엘하 15장, 요한복음 18장', en:'Kidron Valley', origin:'נַחַל קִדְרוֹן', pron:'키드론' },
  '힌놈골짜기': { category:'지명', desc:'예루살렘 남쪽 골짜기. 게헨나(지옥)의 어원.', ref:'여호수아 15장, 예레미야 7장', en:'Valley of Hinnom', origin:'גֵּיא הִנֹּם', pron:'게 힌놈' },
  '베데스다': { category:'지명', desc:'예수께서 38년 된 병자를 고치신 예루살렘의 못.', ref:'요한복음 5장', en:'Bethesda', origin:'Βηθεσδά', pron:'베테스다' },
  '실로암': { category:'지명', desc:'예수께서 맹인을 고치며 씻으라 하신 못.', ref:'요한복음 9장', en:'Siloam', origin:'Σιλωάμ', pron:'실로암' },
  '엠마오': { category:'지명', desc:'부활하신 예수께서 두 제자에게 나타나신 길의 마을.', ref:'누가복음 24장', en:'Emmaus', origin:'Ἐμμαοῦς', pron:'엠마우스' },
  '욥바': { category:'지명', desc:'베드로가 환상을 본 항구. 요나가 배를 탄 곳.', ref:'요나 1장, 사도행전 9장', en:'Joppa', origin:'יָפוֹ', pron:'야포' },
  '룻다': { category:'지명', desc:'베드로가 애니아를 고친 성읍.', ref:'사도행전 9장', en:'Lydda', origin:'Λύδδα', pron:'뤼다' },
  '더베': { category:'지명', desc:'바울이 복음을 전한 소아시아의 도시.', ref:'사도행전 14장', en:'Derbe', origin:'Δέρβη', pron:'데르베' },
  '루스드라': { category:'지명', desc:'바울이 앉은뱅이를 고치고 디모데를 만난 도시.', ref:'사도행전 14장, 16장', en:'Lystra', origin:'Λύστρα', pron:'뤼스트라' },
  '이고니온': { category:'지명', desc:'바울이 복음을 전한 소아시아의 도시.', ref:'사도행전 14장', en:'Iconium', origin:'Ἰκόνιον', pron:'이코니온' },
  '밀레도': { category:'지명', desc:'바울이 에베소 장로들과 작별한 항구.', ref:'사도행전 20장', en:'Miletus', origin:'Μίλητος', pron:'밀레토스' },
  '드로아': { category:'지명', desc:'바울이 마케도니아 환상을 본 항구 도시.', ref:'사도행전 16장', en:'Troas', origin:'Τρῳάς', pron:'트로아스' },
  '살라미': { category:'지명', desc:'바울의 1차 전도여행 중 구브로의 도시.', ref:'사도행전 13장', en:'Salamis', origin:'Σαλαμίς', pron:'살라미스' },
  '바보': { category:'지명', desc:'구브로 섬에서 총독이 회심한 도시.', ref:'사도행전 13장', en:'Paphos', origin:'Πάφος', pron:'파포스' },
  '구브로': { category:'지명', desc:'바나바의 고향인 지중해의 섬. 키프로스.', ref:'사도행전 13장', en:'Cyprus', origin:'Κύπρος', pron:'퀴프로스' },
  '멜리데': { category:'지명', desc:'바울이 로마로 가던 중 난파해 머문 섬. 몰타.', ref:'사도행전 28장', en:'Malta', origin:'Μελίτη', pron:'멜리테' },
  '수가': { category:'지명', desc:'예수께서 사마리아 여인을 만난 우물이 있는 동네.', ref:'요한복음 4장', en:'Sychar', origin:'Συχάρ', pron:'쉬카르' },
  '가나': { category:'지명', desc:'예수께서 첫 표적으로 물을 포도주로 바꾸신 갈릴리 마을.', ref:'요한복음 2장', en:'Cana', origin:'Κανά', pron:'카나' },
  '벳새다': { category:'지명', desc:'베드로·안드레·빌립의 고향.', ref:'요한복음 1장, 마가복음 8장', en:'Bethsaida', origin:'Βηθσαϊδά', pron:'벳사이다' },
  '고라신': { category:'지명', desc:'예수께서 책망하신 갈릴리 호숫가 마을.', ref:'마태복음 11장', en:'Chorazin', origin:'Χοραζίν', pron:'코라진' },
  '데가볼리': { category:'지명', desc:'갈릴리 동남쪽 열 개 도시 지역.', ref:'마가복음 5장', en:'Decapolis', origin:'Δεκάπολις', pron:'데카폴리스' },
  '살렘': { category:'지명', desc:'멜기세덱이 왕으로 다스린 성. 예루살렘의 옛 이름으로 본다.', ref:'창세기 14장, 히브리서 7장', en:'Salem', origin:'שָׁלֵם', pron:'샬렘' },
  '에덴동산': { category:'지명', desc:'에덴의 동산. 아담과 하와가 살던 낙원.', ref:'창세기 2장', en:'Garden of Eden', origin:'גַּן עֵדֶן', pron:'간 에덴' },
};
